#include "bt_via6522.h"
#include <string.h>
static void irq_update(bt_via6522*v){if(v->ifr&v->ier&0x7fu)v->ifr|=0x80u;else v->ifr&=0x7fu;}
static void set_ifr(bt_via6522*v,uint8_t b){v->ifr|=b;irq_update(v);}
static void clear_ifr(bt_via6522*v,uint8_t b){v->ifr&=(uint8_t)~b;irq_update(v);}
static uint8_t pins(const bt_via6522*v,unsigned p){uint8_t l=p?v->ora:v->orb,d=p?v->ddra:v->ddrb,ext=v->port_read?v->port_read(v->io_ctx,p,l,d):0xffu;uint8_t r=(uint8_t)((l&d)|(ext&(uint8_t)~d));if(!p&&(v->acr&0x80u)){r&=0x7fu;if(v->pb7)r|=0x80u;}return r;}
static void notify(bt_via6522*v,unsigned p){if(v->port_write){uint8_t l=p?v->ora:v->orb,d=p?v->ddra:v->ddrb;v->port_write(v->io_ctx,p,l,d,(uint8_t)((l&d)|((uint8_t)~d)));}}
static void control_out(bt_via6522*v){uint8_t ca=(uint8_t)((v->pcr>>1)&7u),cb=(uint8_t)((v->pcr>>5)&7u);if(ca>=6u)v->ca2=(uint8_t)(ca==7u);if(cb>=6u)v->cb2=(uint8_t)(cb==7u);if(v->control_write){v->control_write(v->io_ctx,0u,v->ca2!=0u);v->control_write(v->io_ctx,1u,v->cb2!=0u);}}
void bt_via6522_reset(bt_via6522*v){void*c=v->io_ctx;bt_via_port_read_fn r=v->port_read;bt_via_port_write_fn w=v->port_write;bt_via_control_write_fn cw=v->control_write;memset(v,0,sizeof(*v));v->io_ctx=c;v->port_read=r;v->port_write=w;v->control_write=cw;v->t1c=v->t1l=v->t2c=0xffffu;v->ca1=v->cb1=v->ca2=v->cb2=1u;notify(v,0);notify(v,1);control_out(v);}
void bt_via6522_init(bt_via6522*v,void*c,bt_via_port_read_fn r,bt_via_port_write_fn w,bt_via_control_write_fn cw){if(!v)return;memset(v,0,sizeof(*v));v->io_ctx=c;v->port_read=r;v->port_write=w;v->control_write=cw;bt_via6522_reset(v);}
void bt_via6522_tick(bt_via6522*v,uint64_t cycle){if(!v)return;v->cycle=cycle;if(v->t1_running){if(v->t1c==0u){if(!v->t1_fired||(v->acr&0x40u))set_ifr(v,BT_VIA_IFR_T1);v->t1_fired=1u;if(v->acr&0x80u)v->pb7^=1u;if(v->acr&0x40u)v->t1c=v->t1l;else v->t1c=0xffffu;}else v->t1c--;}if(v->t2_running&&!(v->acr&0x20u)){if(v->t2c==0u){if(!v->t2_fired)set_ifr(v,BT_VIA_IFR_T2);v->t2_fired=1u;v->t2c=0xffffu;}else v->t2c--;}}
uint8_t bt_via6522_peek(const bt_via6522*v,uint8_t r){if(!v)return 0xffu;r&=15u;switch(r){case 0:return pins(v,0);case 1:case 15:return pins(v,1);case 2:return v->ddrb;case 3:return v->ddra;case 4:return (uint8_t)v->t1c;case 5:return (uint8_t)(v->t1c>>8);case 6:return (uint8_t)v->t1l;case 7:return (uint8_t)(v->t1l>>8);case 8:return (uint8_t)v->t2c;case 9:return (uint8_t)(v->t2c>>8);case 10:return v->sr;case 11:return v->acr;case 12:return v->pcr;case 13:return v->ifr;case 14:return (uint8_t)(v->ier|0x80u);default:return 0xffu;}}
uint8_t bt_via6522_read(bt_via6522*v,uint8_t r){uint8_t x;r&=15u;x=bt_via6522_peek(v,r);if(r==0u){clear_ifr(v,(uint8_t)(BT_VIA_IFR_CB1|BT_VIA_IFR_CB2));}else if(r==1u||r==15u){clear_ifr(v,(uint8_t)(BT_VIA_IFR_CA1|(r==1u?BT_VIA_IFR_CA2:0u)));}else if(r==4u)clear_ifr(v,BT_VIA_IFR_T1);else if(r==8u)clear_ifr(v,BT_VIA_IFR_T2);else if(r==10u)clear_ifr(v,BT_VIA_IFR_SR);return x;}
void bt_via6522_write(bt_via6522*v,uint8_t r,uint8_t x){if(!v)return;r&=15u;switch(r){case 0:v->orb=x;clear_ifr(v,(uint8_t)(BT_VIA_IFR_CB1|BT_VIA_IFR_CB2));notify(v,0);break;case 1:case 15:v->ora=x;clear_ifr(v,(uint8_t)(BT_VIA_IFR_CA1|(r==1u?BT_VIA_IFR_CA2:0u)));notify(v,1);break;case 2:v->ddrb=x;notify(v,0);break;case 3:v->ddra=x;notify(v,1);break;case 4:case 6:v->t1l=(uint16_t)((v->t1l&0xff00u)|x);break;case 5:v->t1l=(uint16_t)((v->t1l&0x00ffu)|((uint16_t)x<<8));v->t1c=v->t1l;v->t1_running=1u;v->t1_fired=0u;if(v->acr&0x80u)v->pb7=0u;clear_ifr(v,BT_VIA_IFR_T1);break;case 7:v->t1l=(uint16_t)((v->t1l&0x00ffu)|((uint16_t)x<<8));clear_ifr(v,BT_VIA_IFR_T1);break;case 8:v->t2c=(uint16_t)((v->t2c&0xff00u)|x);break;case 9:v->t2c=(uint16_t)((v->t2c&0x00ffu)|((uint16_t)x<<8));v->t2_running=1u;v->t2_fired=0u;clear_ifr(v,BT_VIA_IFR_T2);break;case 10:v->sr=x;clear_ifr(v,BT_VIA_IFR_SR);/* C10 sealed target-use proof has zero admitted SR accesses. Any activation is outside the Battletech closure. */v->unsupported=1u;break;case 11:v->acr=x;/* The sole admitted VIA2 ACR initialization is $41: T1 free-run, shift mode disabled. */if((x&0x3cu)!=0u)v->unsupported=1u;break;case 12:v->pcr=x;control_out(v);break;case 13:clear_ifr(v,(uint8_t)(x&0x7fu));break;case 14:if(x&0x80u)v->ier|=(uint8_t)(x&0x7fu);else v->ier&=(uint8_t)~x;irq_update(v);break;default:break;}}
static void edge(bt_via6522*v,bool ca,bool level){uint8_t old=ca?v->ca1:v->cb1,positive=ca?(v->pcr&1u):((v->pcr>>4)&1u);if(ca)v->ca1=(uint8_t)level;else v->cb1=(uint8_t)level;if(old!=(uint8_t)level&&((positive&&level)||(!positive&&!level)))set_ifr(v,ca?BT_VIA_IFR_CA1:BT_VIA_IFR_CB1);}
void bt_via6522_set_ca1(bt_via6522*v,bool l){if(v)edge(v,true,l);}
bool bt_via6522_irq(const bt_via6522*v){return v&&(v->ifr&0x80u)!=0u;}
