#include "bt_diagnostic.h"
const char *bt_static_error_name(bt_static_error e){
 switch(e){
  case BT_STATIC_OK:return "OK";case BT_STATIC_ERR_BAD_ARGUMENT:return "BAD_ARGUMENT";case BT_STATIC_ERR_API_VERSION:return "API_VERSION";
  case BT_STATIC_ERR_WRONG_PROFILE:return "WRONG_PROFILE";case BT_STATIC_ERR_WRONG_SYSTEM_ROM:return "WRONG_SYSTEM_ROM";case BT_STATIC_ERR_WRONG_MEDIA:return "WRONG_MEDIA";
  case BT_STATIC_ERR_MEDIA_NOT_READY:return "MEDIA_NOT_READY";case BT_STATIC_ERR_UNSUPPORTED_TARGET_HARDWARE:return "UNSUPPORTED_TARGET_HARDWARE";
  case BT_STATIC_ERR_UNKNOWN_TARGET:return "UNKNOWN_TARGET";case BT_STATIC_ERR_UNKNOWN_EPOCH:return "UNKNOWN_EPOCH";case BT_STATIC_ERR_CPU_JAM:return "CPU_JAM";
  case BT_STATIC_ERR_SYSTEM_ROM_EXIT:return "SYSTEM_ROM_EXIT";case BT_STATIC_ERR_SNAPSHOT_MAGIC:return "SNAPSHOT_MAGIC";case BT_STATIC_ERR_SNAPSHOT_VERSION:return "SNAPSHOT_VERSION";
  case BT_STATIC_ERR_SNAPSHOT_IDENTITY:return "SNAPSHOT_IDENTITY";case BT_STATIC_ERR_SNAPSHOT_TRUNCATED:return "SNAPSHOT_TRUNCATED";case BT_STATIC_ERR_SNAPSHOT_CORRUPT:return "SNAPSHOT_CORRUPT";
  case BT_STATIC_ERR_SNAPSHOT_STATE:return "SNAPSHOT_STATE";case BT_STATIC_ERR_STEP_LIMIT:return "STEP_LIMIT";case BT_STATIC_ERR_INTERNAL:return "INTERNAL";default:return "UNKNOWN_ERROR";
 }
}
