#include "bt_static_core_internal.h"
#include "../media/bt_sha256.h"
#include "../diagnostic/bt_diagnostic.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define BT_AOT_AUTHORITY_SHA256 "dc4ded8f2f3f2c7250241ceaab3acd8ee269fa7ef0b4e97756e7621170662c83"
static const char *const ROM_HASH[4]={
 "89878cea0a268734696de11c4bae593eaaa506465d2029d619c0e0cbccdfa62d",
 "83c60d47047d7beab8e5b7bf6f67f80daa088b7a6a27de0d7e016f6484042721",
 "fd0d53b8480e86163ac98998976c72cc58d5dd8eb824ed7b829774e74213b420",
 "326c289c38753323d7e8167897447cf61ef35189d82eb8d75210ece949adda7c"};
static const char *const MEDIA_HASH[2]={
 "135ac55a444ed8dcf5648b61cf3e1953e4dc342b135bbfcc6c550dd55a3af862",
 "1806a717ee66e6b67652ba7210e82fa150a000986c3ec9234e71fa2fc9ef4769"};
static void *default_alloc(void *ctx,size_t n){(void)ctx;return malloc(n);}static void default_free(void *ctx,void *p){(void)ctx;free(p);}
void *bt_static_alloc(const bt_static_core *c,size_t n){return c&&c->allocator.alloc?c->allocator.alloc(c->allocator.ctx,n):NULL;}
void bt_static_free(const bt_static_core *c,void *p){if(c&&c->allocator.free)c->allocator.free(c->allocator.ctx,p);}
static void digest_hex(const uint8_t d[32],char out[65]){static const char h[]="0123456789abcdef";unsigned i;for(i=0;i<32u;i++){out[i*2u]=h[d[i]>>4];out[i*2u+1u]=h[d[i]&15u];}out[64]=0;}
static int verify_blob(const bt_static_blob *b,size_t n,const char *want,uint8_t save[32]){uint8_t d[32];char hx[65];if(!b||!b->data||b->size!=n)return 0;bt_sha256(b->data,b->size,d);digest_hex(d,hx);if(strcmp(hx,want)!=0)return 0;if(memcmp(b->sha256,(uint8_t[32]){0},32u)!=0&&memcmp(b->sha256,d,32u)!=0)return 0;if(save)memcpy(save,d,32u);return 1;}
void bt_static_set_diag(bt_static_core *c,bt_static_error code,bt_static_stop_reason stop,const char *message){if(!c)return;c->last_stop=stop;c->diag.view.code=code;c->diag.view.stop_reason=stop;c->diag.view.cycle=c->machine.scheduler.cycle;c->diag.view.c64_pc=c->machine.cpu.pc;c->diag.view.drive_pc=c->drive.cpu.pc;snprintf(c->diag.message,sizeof(c->diag.message),"%s",message?message:bt_static_error_name(code));c->diag.view.message=c->diag.message;}
void bt_static_emit_trace(const bt_static_core *c,bt_static_trace_kind k,uint32_t identity,uint16_t pc,uint32_t code,uint64_t value){bt_static_trace_event e;if(!c||!c->trace.fn)return;memset(&e,0,sizeof(e));e.kind=k;e.cycle=c->machine.scheduler.cycle;e.identity_key=identity;e.pc=pc;e.code=code;e.value=value;c->trace.fn(c->trace.ctx,&e);}
static void audio_sink(void *ctx,uint64_t cycle,int16_t sample){bt_static_core*c=(bt_static_core*)ctx;if(!c)return;if(c->audio_count==BT_STATIC_AUDIO_QUEUE_SAMPLES){c->audio_read=(c->audio_read+1u)%BT_STATIC_AUDIO_QUEUE_SAMPLES;c->audio_count--;}if(c->audio_count==0u)c->audio_first_cycle=cycle;c->audio_queue[c->audio_write]=sample;c->audio_write=(c->audio_write+1u)%BT_STATIC_AUDIO_QUEUE_SAMPLES;c->audio_count++;}
static bool c64_aot_rendezvous(void *ctx,uint64_t cyc){return bt_c64_machine_aot_rendezvous(ctx,cyc);}
int bt_static_prepare_runtime(bt_static_core *c){
 if(!c||!c->system_loaded||!c->media_loaded)return 0;
 bt_c06_registry_init(&c->registry);bt_iec_init(&c->iec);
 bt_c64_machine_init(&c->machine,c->basic,c->kernal,c->chargen);
 if(!bt_1541_target_init(&c->drive,&c->registry,&c->iec,c->drive_rom,BT_STATIC_DRIVE_ROM_BYTES))return 0;
 if(!bt_1541_target_attach_side(&c->drive,1u,c->media_bytes[0],BT_D64_SIZE,false))return 0;
 if(!bt_1541_target_attach_side(&c->drive,2u,c->media_bytes[1],BT_D64_SIZE,false))return 0;
 if(!bt_1541_target_select_side(&c->drive,1u))return 0;
 if(!bt_c64_machine_attach_1541(&c->machine,&c->iec,&c->drive))return 0;
 memset(&c->c64_aot,0,sizeof(c->c64_aot));bt_c06_registry_bind_context(&c->registry,&c->machine.cpu,&c->c64_aot);
 if(!bt_aot_set_rendezvous(&c->c64_aot,&c->machine,c64_aot_rendezvous))return 0;
 bt_sid6581_set_sample_sink(&c->machine.sid,c,audio_sink);
 c->audio_read=c->audio_write=c->audio_count=0u;c->audio_first_cycle=0u;c->executing_identity_key=0u;c->executing_pc=0u;c->last_stop=BT_STATIC_STOP_NONE;bt_kernal_target_state_init(&c->kernal_target);
 return 1;
}
uint32_t bt_static_core_api_version(void){return BT_STATIC_CORE_API_VERSION;}uint32_t bt_static_core_snapshot_version(void){return BT_STATIC_CORE_SNAPSHOT_VERSION;}const char *bt_static_core_aot_authority_sha256(void){return BT_AOT_AUTHORITY_SHA256;}
bt_static_core *bt_static_core_create(const bt_static_create_info *info){bt_static_allocator a={0};bt_static_core*c;uint32_t req=BT_STATIC_CORE_API_VERSION;if(info){if(info->struct_size<sizeof(*info))return NULL;req=info->requested_api_version?info->requested_api_version:BT_STATIC_CORE_API_VERSION;a=info->allocator;if((a.alloc==NULL)!=(a.free==NULL))return NULL;}if((req>>16)!=(BT_STATIC_CORE_API_VERSION>>16))return NULL;if(!a.alloc){a.ctx=NULL;a.alloc=default_alloc;a.free=default_free;}c=(bt_static_core*)a.alloc(a.ctx,sizeof(*c));if(!c)return NULL;memset(c,0,sizeof(*c));c->allocator=a;if(info)c->trace=info->trace;c->diag.view.message=c->diag.message;bt_static_set_diag(c,BT_STATIC_OK,BT_STATIC_STOP_NONE,"created; target identities not loaded");return c;}
void bt_static_core_destroy(bt_static_core*c){bt_static_allocator a;if(!c)return;a=c->allocator;memset(c,0,sizeof(*c));a.free(a.ctx,c);}
int bt_static_core_load_system_roms(bt_static_core*c,const bt_static_system_rom_set*r){if(!c||!r)return BT_STATIC_ERR_BAD_ARGUMENT;if(!verify_blob(&r->basic,BT_STATIC_BASIC_BYTES,ROM_HASH[0],c->rom_hash[0])||!verify_blob(&r->kernal,BT_STATIC_KERNAL_BYTES,ROM_HASH[1],c->rom_hash[1])||!verify_blob(&r->chargen,BT_STATIC_CHARGEN_BYTES,ROM_HASH[2],c->rom_hash[2])||!verify_blob(&r->drive1541ii,BT_STATIC_DRIVE_ROM_BYTES,ROM_HASH[3],c->rom_hash[3])){bt_static_set_diag(c,BT_STATIC_ERR_WRONG_SYSTEM_ROM,BT_STATIC_STOP_FATAL,"system ROM identity rejected");return BT_STATIC_ERR_WRONG_SYSTEM_ROM;}memcpy(c->basic,r->basic.data,BT_STATIC_BASIC_BYTES);memcpy(c->kernal,r->kernal.data,BT_STATIC_KERNAL_BYTES);memcpy(c->chargen,r->chargen.data,BT_STATIC_CHARGEN_BYTES);memcpy(c->drive_rom,r->drive1541ii.data,BT_STATIC_DRIVE_ROM_BYTES);c->system_loaded=1u;c->reset_done=0u;bt_static_set_diag(c,BT_STATIC_OK,BT_STATIC_STOP_NONE,"system ROM identities accepted");return BT_STATIC_OK;}
int bt_static_core_load_media_pair(bt_static_core*c,const bt_static_media_pair*m){unsigned i;if(!c||!m)return BT_STATIC_ERR_BAD_ARGUMENT;for(i=0;i<2u;i++)if(!verify_blob(&m->side[i],BT_D64_SIZE,MEDIA_HASH[i],c->media_hash[i])){bt_static_set_diag(c,BT_STATIC_ERR_WRONG_MEDIA,BT_STATIC_STOP_MEDIA_ERROR,"Battletech D64 identity rejected");return BT_STATIC_ERR_WRONG_MEDIA;}for(i=0;i<2u;i++)memcpy(c->media_bytes[i],m->side[i].data,BT_D64_SIZE);c->media_loaded=1u;c->reset_done=0u;bt_static_set_diag(c,BT_STATIC_OK,BT_STATIC_STOP_NONE,"both Battletech D64 sides accepted");return BT_STATIC_OK;}
int bt_static_core_reset(bt_static_core*c,uint64_t seed){if(!c)return BT_STATIC_ERR_BAD_ARGUMENT;if(!c->system_loaded||!c->media_loaded){bt_static_set_diag(c,BT_STATIC_ERR_MEDIA_NOT_READY,BT_STATIC_STOP_MEDIA_ERROR,"system ROMs and both D64 sides are required before reset");return BT_STATIC_ERR_MEDIA_NOT_READY;}if(!bt_static_prepare_runtime(c)){bt_static_set_diag(c,BT_STATIC_ERR_INTERNAL,BT_STATIC_STOP_FATAL,"static core runtime wiring failed");return BT_STATIC_ERR_INTERNAL;}c->deterministic_seed=seed;if(!bt_1541_target_reset(&c->drive)){bt_static_set_diag(c,BT_STATIC_ERR_INTERNAL,BT_STATIC_STOP_FATAL,"1541 target reset failed");return BT_STATIC_ERR_INTERNAL;}cpu6510_reset(&c->machine.cpu);if(!bt_kernal_target_cold_boot(c)){bt_static_set_diag(c,BT_STATIC_ERR_UNKNOWN_TARGET,BT_STATIC_STOP_UNKNOWN_TARGET,"target cold-start bridge rejected sealed media/static identity");return BT_STATIC_ERR_UNKNOWN_TARGET;}c->reset_done=1u;bt_static_set_diag(c,BT_STATIC_OK,BT_STATIC_STOP_NONE,"deterministic target cold reset/bootstrap complete");return BT_STATIC_OK;}
int bt_static_core_select_disk_side(bt_static_core*c,unsigned side){if(!c||!c->reset_done||side<1u||side>2u)return BT_STATIC_ERR_BAD_ARGUMENT;if(!bt_1541_target_select_side(&c->drive,side)){bt_static_set_diag(c,BT_STATIC_ERR_WRONG_MEDIA,BT_STATIC_STOP_MEDIA_ERROR,"disk side selection rejected");return BT_STATIC_ERR_WRONG_MEDIA;}bt_static_emit_trace(c,BT_STATIC_TRACE_MEDIA,0u,c->machine.cpu.pc,side,1u);return BT_STATIC_OK;}
int bt_static_core_eject_disk(bt_static_core*c){if(!c||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;bt_1541_target_eject(&c->drive);bt_static_emit_trace(c,BT_STATIC_TRACE_MEDIA,0u,c->machine.cpu.pc,0u,0u);return BT_STATIC_OK;}
unsigned bt_static_core_active_disk_side(const bt_static_core*c){return c&&c->reset_done?c->drive.active_side:0u;}
int bt_static_core_submit_input(bt_static_core*c,const bt_static_input_event*e){uint32_t t;uint64_t v;if(!c||!e||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;if(e->cycle<c->machine.scheduler.cycle)return BT_STATIC_ERR_BAD_ARGUMENT;switch(e->kind){case BT_STATIC_INPUT_JOYSTICK2:t=BT_C64_EVENT_JOYSTICK2;v=(uint64_t)((uint32_t)e->value&0x1fu);break;case BT_STATIC_INPUT_KEY_MATRIX:t=BT_C64_EVENT_KEY;v=((uint64_t)(e->control&0xffffu))|((uint64_t)(e->value?1u:0u)<<16);break;case BT_STATIC_INPUT_RESTORE:t=BT_C64_EVENT_RESTORE;v=e->value?1u:0u;break;default:return BT_STATIC_ERR_BAD_ARGUMENT;}if(!bt_c64_machine_schedule_input(&c->machine,e->cycle,100u,t,v)){bt_static_set_diag(c,BT_STATIC_ERR_INTERNAL,BT_STATIC_STOP_FATAL,"input event queue rejected event");return BT_STATIC_ERR_INTERNAL;}bt_static_emit_trace(c,BT_STATIC_TRACE_INPUT,0u,c->machine.cpu.pc,(uint32_t)e->kind,v);return BT_STATIC_OK;}
static bt_static_stop_reason map_aot_stop(bt_aot_stop_reason r){switch(r){case BT_AOT_STOP_CPU_JAM:return BT_STATIC_STOP_CPU_JAM;case BT_AOT_STOP_BLOCK_GUARD_UNAVAILABLE:case BT_AOT_STOP_BLOCK_GUARD_REJECTED:case BT_AOT_STOP_TARGET_REJECTED:return BT_STATIC_STOP_UNKNOWN_TARGET;case BT_AOT_STOP_SHADOW_GUARD_REJECTED:case BT_AOT_STOP_SHADOW_PUSH_REJECTED:return BT_STATIC_STOP_UNKNOWN_EPOCH;default:return BT_STATIC_STOP_FATAL;}}
static bt_static_stop_reason c64_one(bt_static_core*c){uint16_t pc,k;int32_t bi;bt_aot_result ar;c64_bus_source src;if(c->machine.failed||bt_1541_target_failed(&c->drive)){uint64_t fail_value=((uint64_t)(c->machine.failed?1u:0u)<<32)|(uint64_t)(uint32_t)bt_1541_target_last_status(&c->drive);bt_static_emit_trace(c,BT_STATIC_TRACE_STOP,c->registry.c64_owner[c->machine.cpu.pc],c->machine.cpu.pc,0x4641494Cu,fail_value);return BT_STATIC_STOP_FATAL;}if(c->machine.cpu.jammed)return BT_STATIC_STOP_CPU_JAM;pc=c->machine.cpu.pc;if(bt_battletech_drive_upload_service(c,pc))return BT_STATIC_STOP_NONE;if(bt_battletech_fastloader_service(c,pc))return BT_STATIC_STOP_NONE;src=c64_bus_cpu_source(&c->machine.bus,pc);/* Bounded KERNAL static services are an atomic system-ROM boundary for IRQ
 delivery.  A pending maskable IRQ is left asserted and is taken immediately after
 the KERNAL service returns to a game-owned PC, avoiding a false static-identity
 claim for a ROM return PC while preserving hardware time and IRQ state. */if(src==C64_BUS_SRC_KERNAL){if(bt_kernal_target_service(c,pc))return BT_STATIC_STOP_NONE;return BT_STATIC_STOP_SYSTEM_ROM_EXIT;}if(c->machine.cpu.nmi_edge_pending||(c->machine.cpu.irq_line&&!c->machine.cpu.irq_sampled)){cpu6510_step_result ir;if(!bt_c06_registry_push_hardware_interrupt(&c->registry,BT_C06_PROCESSOR_C64_6510,pc))return BT_STATIC_STOP_UNKNOWN_EPOCH;ir=cpu6510_service_pending_interrupt(&c->machine.cpu);if(!(ir.serviced_irq||ir.serviced_nmi))return BT_STATIC_STOP_FATAL;return BT_STATIC_STOP_NONE;}if(!bt_c06_registry_set_c64_view(&c->registry,c64_bus_effective_cpu_config(&c->machine.bus)))return BT_STATIC_STOP_FATAL;k=c->registry.c64_owner[pc];if(!k){if(src==C64_BUS_SRC_BASIC)return BT_STATIC_STOP_SYSTEM_ROM_EXIT;return BT_STATIC_STOP_UNKNOWN_EPOCH;}bi=bt_c06_find_block(k,pc);if(bi<0)return BT_STATIC_STOP_UNKNOWN_TARGET;c->executing_identity_key=k;c->executing_pc=pc;bt_static_emit_trace(c,BT_STATIC_TRACE_C64_BLOCK,k,pc,0u,(uint64_t)bi);ar=bt_c06_execute_index(&c->c64_aot,(uint32_t)bi);if(c->machine.failed||bt_1541_target_failed(&c->drive)){uint64_t fail_value=((uint64_t)(c->machine.failed?1u:0u)<<32)|(uint64_t)(uint32_t)bt_1541_target_last_status(&c->drive);bt_static_emit_trace(c,BT_STATIC_TRACE_STOP,k,pc,0x4641494Cu,fail_value);c->executing_identity_key=0u;c->executing_pc=0u;return BT_STATIC_STOP_FATAL;}c->executing_identity_key=0u;c->executing_pc=0u;if(ar.stop_reason!=BT_AOT_STOP_NONE){if(ar.stop_reason==BT_AOT_STOP_INTERRUPT_RENDEZVOUS)return BT_STATIC_STOP_NONE;{uint64_t aot_fail=((uint64_t)(uint32_t)ar.stop_reason<<48)|((uint64_t)(c->machine.failed?1u:0u)<<40)|((uint64_t)(uint32_t)bt_1541_target_last_status(&c->drive)<<32)|(uint64_t)ar.next_pc;bt_static_emit_trace(c,BT_STATIC_TRACE_STOP,k,pc,0x414F5453u,aot_fail);}if(ar.stop_reason==BT_AOT_STOP_TARGET_REJECTED&&bt_kernal_target_dynamic_trampoline(c,pc,ar.next_pc))return BT_STATIC_STOP_NONE;return map_aot_stop(ar.stop_reason);}if(ar.target_class==BT_AOT_TARGET_SYSTEM_ROM_EXIT){if(c64_bus_cpu_source(&c->machine.bus,ar.next_pc)==C64_BUS_SRC_KERNAL&&bt_kernal_target_service(c,ar.next_pc))return BT_STATIC_STOP_NONE;return BT_STATIC_STOP_SYSTEM_ROM_EXIT;}if(ar.target_class==BT_AOT_TARGET_TRAP){if(bt_kernal_target_dynamic_trampoline(c,pc,ar.next_pc))return BT_STATIC_STOP_NONE;return BT_STATIC_STOP_UNKNOWN_TARGET;}if(ar.target_class==BT_AOT_TARGET_STOP)return BT_STATIC_STOP_TARGET_REACHED;return BT_STATIC_STOP_NONE;}
static bt_static_error error_for_stop(bt_static_stop_reason s){switch(s){case BT_STATIC_STOP_SYSTEM_ROM_EXIT:return BT_STATIC_ERR_SYSTEM_ROM_EXIT;case BT_STATIC_STOP_CPU_JAM:return BT_STATIC_ERR_CPU_JAM;case BT_STATIC_STOP_UNKNOWN_TARGET:return BT_STATIC_ERR_UNKNOWN_TARGET;case BT_STATIC_STOP_UNKNOWN_EPOCH:return BT_STATIC_ERR_UNKNOWN_EPOCH;case BT_STATIC_STOP_UNSUPPORTED_TARGET_HARDWARE:return BT_STATIC_ERR_UNSUPPORTED_TARGET_HARDWARE;case BT_STATIC_STOP_STEP_LIMIT:return BT_STATIC_ERR_STEP_LIMIT;case BT_STATIC_STOP_FATAL:return BT_STATIC_ERR_INTERNAL;default:return BT_STATIC_OK;}}
int bt_static_core_run_until_cycle(bt_static_core*c,uint64_t target,uint64_t limit,bt_static_run_result*out){uint64_t start,blocks=0u,frames;bt_static_stop_reason s=BT_STATIC_STOP_NONE;if(!c||!out||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;start=c->machine.scheduler.cycle;if(target<start)return BT_STATIC_ERR_BAD_ARGUMENT;if(limit==0u)limit=1000000u;frames=c->machine.vicii.completed_frames;while(c->machine.scheduler.cycle<target&&blocks<limit){s=c64_one(c);blocks++;if(s!=BT_STATIC_STOP_NONE)break;if(c->machine.vicii.completed_frames!=frames){s=BT_STATIC_STOP_FRAME_READY;break;}}if(s==BT_STATIC_STOP_NONE&&blocks>=limit&&c->machine.scheduler.cycle<target)s=BT_STATIC_STOP_STEP_LIMIT;memset(out,0,sizeof(*out));out->reason=s;out->start_cycle=start;out->end_cycle=c->machine.scheduler.cycle;out->completed_frame=c->machine.vicii.completed_frames;out->c64_pc=c->machine.cpu.pc;out->drive_pc=c->drive.cpu.pc;out->active_disk_side=c->drive.active_side;out->diagnostic_code=(uint32_t)error_for_stop(s);out->native_blocks=blocks;c->last_stop=s;if(s!=BT_STATIC_STOP_NONE&&s!=BT_STATIC_STOP_FRAME_READY&&s!=BT_STATIC_STOP_TARGET_REACHED)bt_static_set_diag(c,error_for_stop(s),s,bt_static_error_name(error_for_stop(s)));bt_static_emit_trace(c,BT_STATIC_TRACE_STOP,c->registry.c64_owner[c->machine.cpu.pc],c->machine.cpu.pc,(uint32_t)s,blocks);return (int)error_for_stop(s);}
int bt_static_core_advance_frame(bt_static_core*c,uint64_t limit,bt_static_run_result*r){uint64_t target;if(!c||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;target=(c->machine.vicii.completed_frames+1u)*(uint64_t)BT_STATIC_CORE_PAL_CYCLES_PER_FRAME;if(target<=c->machine.scheduler.cycle)target=c->machine.scheduler.cycle+BT_STATIC_CORE_PAL_CYCLES_PER_FRAME;return bt_static_core_run_until_cycle(c,target,limit,r);}
int bt_static_core_get_video(const bt_static_core*c,bt_static_video_frame*f){if(!c||!f||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;f->pixels=bt_vicii6569_framebuffer(&c->machine.vicii);f->width=BT_STATIC_CORE_FRAME_WIDTH;f->height=BT_STATIC_CORE_FRAME_HEIGHT;f->pitch=BT_STATIC_CORE_FRAME_WIDTH;f->pixel_format=1u;f->completed_cycle=c->machine.scheduler.cycle;f->frame_number=c->machine.vicii.completed_frames;return BT_STATIC_OK;}
size_t bt_static_core_audio_available(const bt_static_core*c){return c?c->audio_count:0u;}size_t bt_static_core_audio_read(bt_static_core*c,int16_t*out,size_t cap){size_t n=0;if(!c||(!out&&cap))return 0u;while(n<cap&&c->audio_count){out[n++]=c->audio_queue[c->audio_read];c->audio_read=(c->audio_read+1u)%BT_STATIC_AUDIO_QUEUE_SAMPLES;c->audio_count--;}if(!c->audio_count)c->audio_first_cycle=0u;return n;}void bt_static_core_audio_clear(bt_static_core*c){if(c){c->audio_read=c->audio_write=c->audio_count=0u;c->audio_first_cycle=0u;}}
size_t bt_static_core_snapshot_size(const bt_static_core*c){return bt_static_snapshot_size_internal(c);}int bt_static_core_snapshot_save(const bt_static_core*c,void*d,size_t n){return bt_static_snapshot_save_internal(c,d,n);}int bt_static_core_snapshot_load(bt_static_core*c,const void*s,size_t n){return bt_static_snapshot_load_internal(c,s,n);}int bt_static_core_state_sha256(const bt_static_core*c,uint8_t o[32]){return bt_static_snapshot_state_hash_internal(c,o);}

#define BT_PERSIST_MEDIA_MAGIC "BTD64OV1"
#define BT_PERSIST_MEDIA_VERSION 1u
#define BT_PERSIST_MEDIA_HEADER 128u
#define BT_PERSIST_MEDIA_ENTRY 260u
static void pm_w16(uint8_t*p,uint16_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);}
static void pm_w32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);p[2]=(uint8_t)(v>>16);p[3]=(uint8_t)(v>>24);}
static void pm_w64(uint8_t*p,uint64_t v){unsigned i;for(i=0;i<8u;i++)p[i]=(uint8_t)(v>>(8u*i));}
static uint16_t pm_r16(const uint8_t*p){return (uint16_t)(p[0]|((uint16_t)p[1]<<8));}
static uint32_t pm_r32(const uint8_t*p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static uint64_t pm_r64(const uint8_t*p){uint64_t v=0;unsigned i;for(i=0;i<8u;i++)v|=(uint64_t)p[i]<<(8u*i);return v;}
static unsigned pm_overlay_used(const bt_d64_image*d){unsigned i,n=0;if(!d)return 0;for(i=0;i<d->overlay_count&&i<BT_D64_SECTORS;i++)if(d->overlay[i].used)n++;return n;}
static const bt_d64_overlay_entry *pm_overlay_index(const bt_d64_image*d,uint16_t idx){unsigned i;if(!d)return NULL;for(i=0;i<d->overlay_count&&i<BT_D64_SECTORS;i++)if(d->overlay[i].used&&d->overlay[i].sector_index==idx)return &d->overlay[i];return NULL;}
size_t bt_static_core_persistent_media_size(const bt_static_core*c){size_t n;if(!c||!c->reset_done)return 0u;n=(size_t)pm_overlay_used(&c->drive.sides[0])+(size_t)pm_overlay_used(&c->drive.sides[1]);return BT_PERSIST_MEDIA_HEADER+n*BT_PERSIST_MEDIA_ENTRY;}
int bt_static_core_persistent_media_export(const bt_static_core*c,void*destination,size_t size){
    uint8_t*h=(uint8_t*)destination,*p,*e,dig[32];size_t need,payload;unsigned side,idx,cnt[2];
    if(!c||!destination||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;
    need=bt_static_core_persistent_media_size(c);if(size<need)return BT_STATIC_ERR_BAD_ARGUMENT;
    cnt[0]=pm_overlay_used(&c->drive.sides[0]);cnt[1]=pm_overlay_used(&c->drive.sides[1]);payload=need-BT_PERSIST_MEDIA_HEADER;
    memset(h,0,BT_PERSIST_MEDIA_HEADER);memcpy(h,BT_PERSIST_MEDIA_MAGIC,8u);pm_w32(h+8u,BT_PERSIST_MEDIA_VERSION);pm_w32(h+12u,BT_PERSIST_MEDIA_HEADER);
    memcpy(h+16u,c->media_hash[0],32u);memcpy(h+48u,c->media_hash[1],32u);pm_w32(h+80u,cnt[0]);pm_w32(h+84u,cnt[1]);pm_w64(h+88u,(uint64_t)payload);
    p=h+BT_PERSIST_MEDIA_HEADER;
    for(side=0u;side<2u;side++)for(idx=0u;idx<BT_D64_SECTORS;idx++){const bt_d64_overlay_entry*o=pm_overlay_index(&c->drive.sides[side],(uint16_t)idx);if(!o)continue;e=p;p+=BT_PERSIST_MEDIA_ENTRY;e[0]=(uint8_t)(side+1u);e[1]=0u;pm_w16(e+2u,(uint16_t)idx);memcpy(e+4u,o->bytes,BT_D64_SECTOR_SIZE);}
    if((size_t)(p-(h+BT_PERSIST_MEDIA_HEADER))!=payload)return BT_STATIC_ERR_INTERNAL;
    bt_sha256(h+BT_PERSIST_MEDIA_HEADER,payload,dig);memcpy(h+96u,dig,32u);return BT_STATIC_OK;
}
int bt_static_core_persistent_media_import(bt_static_core*c,const void*source,size_t size){
    const uint8_t*h=(const uint8_t*)source,*p;uint8_t dig[32],seen[2][BT_D64_SECTORS];uint32_t cnt[2],got[2]={0,0};uint64_t payload;size_t need,n,i;unsigned last_side=0u,last_idx=0u;bool have_last=false;
    if(!c||!source||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;
    if(size<BT_PERSIST_MEDIA_HEADER)return BT_STATIC_ERR_BAD_ARGUMENT;
    if(memcmp(h,BT_PERSIST_MEDIA_MAGIC,8u)!=0||pm_r32(h+8u)!=BT_PERSIST_MEDIA_VERSION||pm_r32(h+12u)!=BT_PERSIST_MEDIA_HEADER)return BT_STATIC_ERR_BAD_ARGUMENT;
    if(memcmp(h+16u,c->media_hash[0],32u)!=0||memcmp(h+48u,c->media_hash[1],32u)!=0)return BT_STATIC_ERR_WRONG_MEDIA;
    cnt[0]=pm_r32(h+80u);cnt[1]=pm_r32(h+84u);if(cnt[0]>BT_D64_SECTORS||cnt[1]>BT_D64_SECTORS)return BT_STATIC_ERR_BAD_ARGUMENT;
    payload=pm_r64(h+88u);if(payload>(uint64_t)SIZE_MAX)return BT_STATIC_ERR_BAD_ARGUMENT;need=BT_PERSIST_MEDIA_HEADER+(size_t)payload;if(need!=size||(size_t)payload!=((size_t)cnt[0]+cnt[1])*BT_PERSIST_MEDIA_ENTRY)return BT_STATIC_ERR_BAD_ARGUMENT;
    bt_sha256(h+BT_PERSIST_MEDIA_HEADER,(size_t)payload,dig);if(memcmp(dig,h+96u,32u)!=0)return BT_STATIC_ERR_SNAPSHOT_CORRUPT;
    memset(seen,0,sizeof(seen));p=h+BT_PERSIST_MEDIA_HEADER;n=(size_t)cnt[0]+cnt[1];
    for(i=0;i<n;i++,p+=BT_PERSIST_MEDIA_ENTRY){unsigned side=p[0],idx=pm_r16(p+2u);if((side!=1u&&side!=2u)||p[1]!=0u||idx>=BT_D64_SECTORS||seen[side-1u][idx])return BT_STATIC_ERR_BAD_ARGUMENT;if(have_last&&(side<last_side||(side==last_side&&idx<=last_idx)))return BT_STATIC_ERR_BAD_ARGUMENT;have_last=true;last_side=side;last_idx=idx;seen[side-1u][idx]=1u;got[side-1u]++;}
    if(got[0]!=cnt[0]||got[1]!=cnt[1])return BT_STATIC_ERR_BAD_ARGUMENT;
    bt_d64_clear_overlay(&c->drive.sides[0]);bt_d64_clear_overlay(&c->drive.sides[1]);p=h+BT_PERSIST_MEDIA_HEADER;
    for(i=0;i<n;i++,p+=BT_PERSIST_MEDIA_ENTRY){bt_d64_image*d=&c->drive.sides[p[0]-1u];bt_d64_overlay_entry*o=&d->overlay[d->overlay_count++];o->sector_index=pm_r16(p+2u);o->used=1u;memcpy(o->bytes,p+4u,BT_D64_SECTOR_SIZE);}
    if(c->drive.inserted&&!bt_1541_target_select_side(&c->drive,c->drive.active_side))return BT_STATIC_ERR_INTERNAL;
    bt_static_emit_trace(c,BT_STATIC_TRACE_MEDIA,0u,c->machine.cpu.pc,0x50525354u,((uint64_t)cnt[0]<<32)|cnt[1]);return BT_STATIC_OK;
}
int bt_static_core_set_trace_hook(bt_static_core*c,bt_static_trace_hook h){if(!c)return BT_STATIC_ERR_BAD_ARGUMENT;c->trace=h;return BT_STATIC_OK;}int bt_static_core_get_status(const bt_static_core*c,bt_static_status*s){if(!c||!s)return BT_STATIC_ERR_BAD_ARGUMENT;memset(s,0,sizeof(*s));s->cycle=c->machine.scheduler.cycle;s->completed_frame=c->machine.vicii.completed_frames;s->c64_pc=c->machine.cpu.pc;s->drive_pc=c->drive.cpu.pc;s->active_disk_side=c->drive.active_side;s->media_inserted=c->drive.inserted;s->stop_reason=c->last_stop;s->error=c->diag.view.code;return BT_STATIC_OK;}const bt_static_diagnostic *bt_static_core_last_diagnostic(const bt_static_core*c){return c?&c->diag.view:NULL;}
