#ifndef UNICODE
#define UNICODE
#endif
#include <windows.h>
#include <commdlg.h>
#include <shellapi.h>
#include <wincrypt.h>
#include <stdint.h>
#include <stdio.h>
#include <wchar.h>
#include "../../version.h"
#include "../common/battletech_frontend_ipc.h"

#define wWinMain battletech_launcher_main

#define COUNT_OF(a) (sizeof(a)/sizeof((a)[0]))
#define GAME_TITLE L"BattleTech: The Crescent Hawk's Inception (C64)"
#define WM_GAME_RETURN (WM_APP+0x314)
#define BINDING_COUNT 7

enum {
 CMD_BROWSE=100,CMD_RUN,CMD_PLAY,CMD_RESET,CMD_AUDIO,CMD_SETTINGS,CMD_CONTROLS,
 CMD_FULLSCREEN,CMD_AUTORUN,CMD_SAVE,CMD_LOAD,CMD_SCREENSHOT,CMD_SAVE_FOLDER,
 CMD_GUIDE,CMD_ABOUT,CMD_EXIT,
 TOOL_BROWSE=200,TOOL_PLAY,TOOL_RESET,TOOL_AUDIO,TOOL_SETTINGS,TOOL_CONTROLS,
 TOOL_FULLSCREEN,TOOL_AUTORUN,TIMER_GAME=1
};

static HINSTANCE g_instance;
static HWND g_main,g_video,g_browse,g_play,g_reset,g_audio,g_settings_button,g_controls_button,g_fullscreen,g_autorun,g_status;
static HWND g_game_window,g_settings_window,g_audio_window,g_controls_window,g_info_window;
static HANDLE g_game,g_resume_event,g_save_event,g_load_event,g_capture_event,g_audio_event,g_audio_mapping;
static DWORD g_game_pid;
static HMENU g_menu;
static wchar_t g_directory[32768],g_media_directory[32768],g_ini_path[32768];
static int g_media_ready,g_paused,g_pending_restart,g_pending_exit,g_game_connected;
static ULONGLONG g_force_close_at;
static int g_capture_action=-1;
static int g_fullscreen_setting,g_correct_aspect,g_vsync,g_scale,g_pause_focus,g_auto_run;
static int g_audio_enabled,g_volume,g_latency,g_input_source,g_deadzone;
static UINT g_bindings[BINDING_COUNT];
static const UINT g_default_bindings[BINDING_COUNT]={VK_UP,VK_DOWN,VK_LEFT,VK_RIGHT,'Z',VK_SPACE,VK_RETURN};
static wchar_t g_log_path[32768];
static int apply_live_audio_settings(void);

static int join_path(wchar_t*out,size_t count,const wchar_t*a,const wchar_t*b){int n;if(!out||!count||!a||!b)return 0;n=_snwprintf(out,count,L"%s\\%s",a,b);if(n<0||(size_t)n>=count){out[0]=0;return 0;}return 1;}
static int file_exists(const wchar_t*path){DWORD a=GetFileAttributesW(path);return a!=INVALID_FILE_ATTRIBUTES&&!(a&FILE_ATTRIBUTE_DIRECTORY);}
static void font(HWND w){if(w)SendMessageW(w,WM_SETFONT,(WPARAM)GetStockObject(DEFAULT_GUI_FONT),TRUE);}
static void status(const wchar_t*text){if(!g_status)return;SetWindowTextW(g_status,text);NotifyWinEvent(EVENT_OBJECT_VALUECHANGE,g_status,OBJID_CLIENT,CHILDID_SELF);}
static void write_number(const wchar_t*section,const wchar_t*key,int value){wchar_t text[24];_snwprintf(text,COUNT_OF(text),L"%d",value);WritePrivateProfileStringW(section,key,text,g_ini_path);}
static int frontend_key(UINT key){return key==VK_ESCAPE||(key>=VK_F1&&key<=VK_F8);}
static int reserved_game_key(UINT key){return key=='P'||key=='M'||key==VK_F11||key==VK_CONTROL;}
static int valid_binding(UINT key){return key>0u&&key<255u&&!frontend_key(key)&&!reserved_game_key(key);}

/* IsDialogMessage supplies the standard Tab/Shift+Tab behavior. Handle Tab
   explicitly so multiline read-only edit controls cannot retain it. */
static int route_dialog_keyboard(HWND dialog,MSG*message){
 HWND focused,next;BOOL previous;
 if(!dialog||!message||message->message!=WM_KEYDOWN||message->wParam!=VK_TAB)return dialog&&IsDialogMessageW(dialog,message);
 if(!IsWindow(dialog)||!IsWindowVisible(dialog)||!IsWindowEnabled(dialog))return 0;
 focused=GetFocus();
 if(!focused||(focused!=dialog&&!IsChild(dialog,focused)))return 0;
 previous=GetKeyState(VK_SHIFT)<0?TRUE:FALSE;
 next=GetNextDlgTabItem(dialog,focused,previous);
 if(!next||next==focused)return 0;
 SetFocus(next);
 return 1;
}

/* Keep every existing dialog-routing site on the same navigation policy,
   including the Welcome-only message loop used before Launcher is created. */
#define IsDialogMessageW(dialog,message) route_dialog_keyboard((dialog),(message))

static void settings_defaults(void){
 g_fullscreen_setting=0;g_correct_aspect=1;g_vsync=0;g_scale=0;g_pause_focus=1;g_auto_run=0;
 g_audio_enabled=1;g_volume=70;g_latency=60;g_input_source=2;g_deadzone=35;
 memcpy(g_bindings,g_default_bindings,sizeof(g_default_bindings));
}

static void load_settings(void){
 unsigned i,j;int bindings_valid=1;wchar_t key[32];settings_defaults();
 g_fullscreen_setting=GetPrivateProfileIntW(L"Frontend",L"FullScreen",g_fullscreen_setting,g_ini_path);
 g_correct_aspect=GetPrivateProfileIntW(L"Frontend",L"CorrectAspect",g_correct_aspect,g_ini_path);
 g_vsync=GetPrivateProfileIntW(L"Frontend",L"VSync",g_vsync,g_ini_path);
 g_scale=GetPrivateProfileIntW(L"Frontend",L"IntegerScale",g_scale,g_ini_path);
 g_pause_focus=GetPrivateProfileIntW(L"Frontend",L"PauseOnFocusLoss",g_pause_focus,g_ini_path);
 g_auto_run=GetPrivateProfileIntW(L"Frontend",L"AutoRun",g_auto_run,g_ini_path);
 g_audio_enabled=GetPrivateProfileIntW(L"Audio",L"Enabled",g_audio_enabled,g_ini_path);
 g_volume=GetPrivateProfileIntW(L"Audio",L"Volume",g_volume,g_ini_path);
 g_latency=GetPrivateProfileIntW(L"Audio",L"LatencyMs",g_latency,g_ini_path);
 g_input_source=GetPrivateProfileIntW(L"Input",L"Source",g_input_source,g_ini_path);
 g_deadzone=GetPrivateProfileIntW(L"Input",L"GamepadDeadzonePercent",g_deadzone,g_ini_path);
 if(g_input_source<0||g_input_source>2)g_input_source=2;
 if(g_deadzone<10||g_deadzone>90)g_deadzone=35;
 if(g_scale<0||g_scale>4)g_scale=0;
 if(g_volume!=0&&g_volume!=25&&g_volume!=50&&g_volume!=70&&g_volume!=100)g_volume=70;
 if(g_latency!=20&&g_latency!=40&&g_latency!=60&&g_latency!=80&&g_latency!=120&&g_latency!=250)g_latency=60;
 for(i=0;i<BINDING_COUNT;i++){_snwprintf(key,COUNT_OF(key),L"Action%u",i);g_bindings[i]=(UINT)GetPrivateProfileIntW(L"Keyboard",key,(int)g_bindings[i],g_ini_path);}
 g_fullscreen_setting=g_fullscreen_setting?1:0;g_correct_aspect=g_correct_aspect?1:0;g_vsync=g_vsync?1:0;g_pause_focus=g_pause_focus?1:0;g_auto_run=g_auto_run?1:0;g_audio_enabled=g_audio_enabled?1:0;
 for(i=0;i<BINDING_COUNT;i++){if(!valid_binding(g_bindings[i]))bindings_valid=0;for(j=0;j<i;j++)if(g_bindings[i]==g_bindings[j])bindings_valid=0;}
 if(!bindings_valid)memcpy(g_bindings,g_default_bindings,sizeof(g_default_bindings));
}

static void save_settings(void){
 unsigned i;wchar_t key[32];
 write_number(L"Frontend",L"FullScreen",g_fullscreen_setting);write_number(L"Frontend",L"CorrectAspect",g_correct_aspect);
 write_number(L"Frontend",L"VSync",g_vsync);write_number(L"Frontend",L"IntegerScale",g_scale);
 write_number(L"Frontend",L"PauseOnFocusLoss",g_pause_focus);write_number(L"Frontend",L"AutoRun",g_auto_run);
 write_number(L"Audio",L"Enabled",g_audio_enabled);write_number(L"Audio",L"Volume",g_volume);write_number(L"Audio",L"LatencyMs",g_latency);
 write_number(L"Input",L"Source",g_input_source);write_number(L"Input",L"GamepadDeadzonePercent",g_deadzone);
 for(i=0;i<BINDING_COUNT;i++){_snwprintf(key,COUNT_OF(key),L"Action%u",i);write_number(L"Keyboard",key,(int)g_bindings[i]);}
}

static int file_sha256_matches(const wchar_t*path,const BYTE expected[32]){HCRYPTPROV provider=0;HCRYPTHASH hash=0;HANDLE file=INVALID_HANDLE_VALUE;BYTE buffer[65536],digest[32];DWORD got,size=sizeof(digest);int ok=0;if(!CryptAcquireContextW(&provider,NULL,MS_ENH_RSA_AES_PROV_W,PROV_RSA_AES,CRYPT_VERIFYCONTEXT))goto done;if(!CryptCreateHash(provider,CALG_SHA_256,0,0,&hash))goto done;file=CreateFileW(path,GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_SEQUENTIAL_SCAN,NULL);if(file==INVALID_HANDLE_VALUE)goto done;for(;;){if(!ReadFile(file,buffer,sizeof(buffer),&got,NULL))goto done;if(!got)break;if(!CryptHashData(hash,buffer,got,0))goto done;}if(!CryptGetHashParam(hash,HP_HASHVAL,digest,&size,0)||size!=sizeof(digest))goto done;ok=memcmp(digest,expected,sizeof(digest))==0;done:if(file!=INVALID_HANDLE_VALUE)CloseHandle(file);if(hash)CryptDestroyHash(hash);if(provider)CryptReleaseContext(provider,0);return ok;}
static int media_pair_status(const wchar_t*directory){static const BYTE hash0[32]={0x13,0x5a,0xc5,0x5a,0x44,0x4e,0xd8,0xdc,0xf5,0x64,0x8b,0x61,0xcf,0x3e,0x19,0x53,0xe4,0xdc,0x34,0x2b,0x13,0x5b,0xbf,0xcc,0x6c,0x55,0x0d,0xd5,0x5a,0x3a,0xf8,0x62};static const BYTE hash1[32]={0x18,0x06,0xa7,0x17,0xee,0x66,0xe6,0xb6,0x76,0x52,0xba,0x72,0x10,0xe8,0x2f,0xa1,0x50,0xa0,0x00,0x98,0x6c,0x3e,0xc9,0x23,0x4e,0x71,0xfa,0x2f,0xc9,0xef,0x47,0x69};wchar_t a[32768],b[32768];if(!directory||!*directory||!join_path(a,COUNT_OF(a),directory,L"BATTLET0.D64")||!join_path(b,COUNT_OF(b),directory,L"BATTLET1.D64")||!file_exists(a)||!file_exists(b))return 0;return file_sha256_matches(a,hash0)&&file_sha256_matches(b,hash1)?1:-1;}

static void select_media(void){
 wchar_t selected[32768]={0},initial[32768],*slash;OPENFILENAMEW ofn;
 ZeroMemory(&ofn,sizeof(ofn));if(g_media_directory[0])wcsncpy(initial,g_media_directory,COUNT_OF(initial)-1);else join_path(initial,COUNT_OF(initial),g_directory,L"Rom");initial[COUNT_OF(initial)-1]=0;
 ofn.lStructSize=sizeof(ofn);ofn.hwndOwner=g_main;ofn.lpstrTitle=L"Select a BattleTech C64 disk image";
 ofn.lpstrFilter=L"Commodore 64 disk images (*.D64)\0*.D64\0All files (*.*)\0*.*\0\0";ofn.lpstrFile=selected;ofn.nMaxFile=COUNT_OF(selected);ofn.lpstrInitialDir=initial;ofn.Flags=OFN_FILEMUSTEXIST|OFN_PATHMUSTEXIST|OFN_HIDEREADONLY;
 if(!GetOpenFileNameW(&ofn))return;
 slash=wcsrchr(selected,L'\\');if(!slash)return;*slash=0;
 {int media_status=media_pair_status(selected);if(!media_status){MessageBoxW(g_main,L"That folder must contain both BATTLET0.D64 and BATTLET1.D64.",L"BattleTech C64 media",MB_OK|MB_ICONERROR);return;}if(media_status<0){MessageBoxW(g_main,L"Those files are not the verified BattleTech C64 disk images required by this recompilation.",L"BattleTech C64 media",MB_OK|MB_ICONERROR);return;}}
 wcsncpy(g_media_directory,selected,COUNT_OF(g_media_directory)-1);g_media_directory[COUNT_OF(g_media_directory)-1]=0;g_media_ready=1;
 WritePrivateProfileStringW(L"Frontend",L"RomFolder",g_media_directory,g_ini_path);status(L"Both verified BattleTech disk images are ready. Select Run or press F7.");
}

typedef struct InfoData{HWND text,close,owner;const wchar_t*body;}InfoData;
static LRESULT CALLBACK InfoProc(HWND w,UINT m,WPARAM wp,LPARAM lp){
 InfoData*d=(InfoData*)GetWindowLongPtrW(w,GWLP_USERDATA);
 if(m==WM_CREATE){d=(InfoData*)((CREATESTRUCTW*)lp)->lpCreateParams;SetWindowLongPtrW(w,GWLP_USERDATA,(LONG_PTR)d);d->text=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",d->body,WS_CHILD|WS_VISIBLE|WS_TABSTOP|ES_LEFT|ES_MULTILINE|ES_READONLY|ES_AUTOVSCROLL|WS_VSCROLL,16,16,10,10,w,NULL,g_instance,NULL);d->close=CreateWindowW(L"BUTTON",L"&Close",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,0,0,100,32,w,(HMENU)IDOK,g_instance,NULL);font(d->text);font(d->close);SetFocus(d->close);return 0;}
 if(m==WM_SIZE&&d){RECT r;int width,height;GetClientRect(w,&r);width=r.right>0?r.right:1;height=r.bottom>0?r.bottom:1;MoveWindow(d->text,16,16,width>32?width-32:1,height>72?height-72:1,TRUE);MoveWindow(d->close,width>100?(width-100)/2:0,height>44?height-44:0,100,32,TRUE);return 0;}
 if(m==WM_COMMAND&&(LOWORD(wp)==IDOK||LOWORD(wp)==IDCANCEL)){DestroyWindow(w);return 0;}if((m==WM_KEYDOWN&&wp==VK_ESCAPE)||m==WM_CLOSE){DestroyWindow(w);return 0;}
 if(m==WM_DESTROY&&d){if(d->owner&&IsWindow(d->owner)){EnableWindow(d->owner,TRUE);SetForegroundWindow(d->owner);}HeapFree(GetProcessHeap(),0,d);g_info_window=NULL;return 0;}return DefWindowProcW(w,m,wp,lp);
}

static void show_information(HWND owner,const wchar_t*title,const wchar_t*body,int width,int height){
 WNDCLASSW wc;InfoData*d;if(g_info_window){d=(InfoData*)GetWindowLongPtrW(g_info_window,GWLP_USERDATA);if(d&&d->text){d->body=body;SetWindowTextW(d->text,body);}SetWindowTextW(g_info_window,title);ShowWindow(g_info_window,SW_SHOWNORMAL);BringWindowToTop(g_info_window);SetForegroundWindow(g_info_window);return;}
 ZeroMemory(&wc,sizeof(wc));wc.lpfnWndProc=InfoProc;wc.hInstance=g_instance;wc.lpszClassName=L"BattleTechC64Information";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);
 d=(InfoData*)HeapAlloc(GetProcessHeap(),HEAP_ZERO_MEMORY,sizeof(*d));if(!d)return;d->owner=owner;d->body=body;
 g_info_window=CreateWindowExW(WS_EX_CONTROLPARENT|WS_EX_DLGMODALFRAME,wc.lpszClassName,title,WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,width,height,owner,NULL,g_instance,d);if(!g_info_window){HeapFree(GetProcessHeap(),0,d);return;}EnableWindow(owner,FALSE);BringWindowToTop(g_info_window);SetForegroundWindow(g_info_window);
}

static void show_guide(HWND owner){show_information(owner,L"Controls Guide",
 L"C64 keyboard and joystick\r\nArrow keys - joystick port 2 directions\r\nZ or Ctrl - Fire\r\nSpace - C64 Space/menu\r\nEnter - C64 Return\r\n\r\nGamepad\r\nD-pad or left stick - joystick directions\r\nSouth face button - Fire\r\nStart - C64 Space/menu\r\n\r\nLauncher navigation\r\nTab - Next control\r\nShift+Tab - Previous control\r\n\r\nLauncher shortcuts\r\nF1 - Controls guide\r\nF2 - Save snapshot\r\nF3 - Load snapshot\r\nF4 - Settings\r\nF5 - Controls\r\nF6 - Audio\r\nF7 - Run selected media\r\nF8 - Capture game frame\r\nEscape - Switch between the game and Launcher",
 620,540);}

static void show_welcome(void){show_information(NULL,L"Welcome",
 L"Welcome to BattleTech: The Crescent Hawk's Inception (C64) Static Recompilation\r\n\r\nFrontend navigation\r\nTab - Next control\r\nShift+Tab - Previous control\r\n\r\nFrontend shortcuts\r\nEscape - Switch between the game and Launcher\r\nF1 - Controls and shortcut guide\r\nF2 - Save snapshot\r\nF3 - Load snapshot\r\nF4 - Settings\r\nF5 - Controls\r\nF6 - Audio\r\nF7 - Run the selected media\r\nF8 - Capture the current game frame\r\n\r\nMedia: BATTLET0.D64 and BATTLET1.D64\r\nDefault folder: Rom\r\nThe original D64 files are never modified.",
 620,500);}

typedef struct SettingsData{HWND fullscreen,aspect,vsync,pause_focus,scale;}SettingsData;
static int combo_index(const int*values,size_t count,int value){size_t i;for(i=0;i<count;i++)if(values[i]==value)return (int)i;return 0;}
static LRESULT CALLBACK SettingsProc(HWND w,UINT m,WPARAM wp,LPARAM lp){
 static SettingsData d;static const int scales[]={0,1,2,3,4};(void)lp;
 if(m==WM_CREATE){HWND heading,scale_label,note,ok,cancel;const wchar_t*items[]={L"Fit window",L"1x",L"2x",L"3x",L"4x"};unsigned i;ZeroMemory(&d,sizeof(d));heading=CreateWindowW(L"STATIC",L"Video",WS_CHILD|WS_VISIBLE,18,14,200,22,w,NULL,g_instance,NULL);d.fullscreen=CreateWindowW(L"BUTTON",L"Start gameplay in &full screen",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX,18,40,320,28,w,NULL,g_instance,NULL);d.aspect=CreateWindowW(L"BUTTON",L"Correct C64 display to &4:3",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX,18,70,320,28,w,NULL,g_instance,NULL);d.vsync=CreateWindowW(L"BUTTON",L"Use &vertical synchronization",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX,18,100,320,28,w,NULL,g_instance,NULL);scale_label=CreateWindowW(L"STATIC",L"&Scale:",WS_CHILD|WS_VISIBLE,362,44,70,22,w,NULL,g_instance,NULL);d.scale=CreateWindowW(L"COMBOBOX",L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|CBS_DROPDOWNLIST,430,40,150,180,w,NULL,g_instance,NULL);for(i=0;i<COUNT_OF(items);i++)SendMessageW(d.scale,CB_ADDSTRING,0,(LPARAM)items[i]);d.pause_focus=CreateWindowW(L"BUTTON",L"&Pause when the game loses focus",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX,18,146,390,28,w,NULL,g_instance,NULL);note=CreateWindowW(L"STATIC",L"Changes apply the next time gameplay starts.",WS_CHILD|WS_VISIBLE,18,186,562,24,w,NULL,g_instance,NULL);ok=CreateWindowW(L"BUTTON",L"OK",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,352,226,105,32,w,(HMENU)IDOK,g_instance,NULL);cancel=CreateWindowW(L"BUTTON",L"Cancel",WS_CHILD|WS_VISIBLE|WS_TABSTOP,475,226,105,32,w,(HMENU)IDCANCEL,g_instance,NULL);font(heading);font(d.fullscreen);font(d.aspect);font(d.vsync);font(scale_label);font(d.scale);font(d.pause_focus);font(note);font(ok);font(cancel);SendMessageW(d.fullscreen,BM_SETCHECK,g_fullscreen_setting?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(d.aspect,BM_SETCHECK,g_correct_aspect?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(d.vsync,BM_SETCHECK,g_vsync?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(d.pause_focus,BM_SETCHECK,g_pause_focus?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(d.scale,CB_SETCURSEL,combo_index(scales,COUNT_OF(scales),g_scale),0);SetFocus(d.fullscreen);return 0;}
 if(m==WM_COMMAND){if(LOWORD(wp)==IDOK){int s;g_fullscreen_setting=SendMessageW(d.fullscreen,BM_GETCHECK,0,0)==BST_CHECKED;g_correct_aspect=SendMessageW(d.aspect,BM_GETCHECK,0,0)==BST_CHECKED;g_vsync=SendMessageW(d.vsync,BM_GETCHECK,0,0)==BST_CHECKED;g_pause_focus=SendMessageW(d.pause_focus,BM_GETCHECK,0,0)==BST_CHECKED;s=(int)SendMessageW(d.scale,CB_GETCURSEL,0,0);if(s>=0&&s<(int)COUNT_OF(scales))g_scale=scales[s];save_settings();status(L"Settings saved. They apply when gameplay next starts.");SendMessageW(g_fullscreen,BM_SETCHECK,g_fullscreen_setting?BST_CHECKED:BST_UNCHECKED,0);DestroyWindow(w);return 0;}if(LOWORD(wp)==IDCANCEL){DestroyWindow(w);return 0;}}
 if((m==WM_KEYDOWN&&wp==VK_ESCAPE)||m==WM_CLOSE){DestroyWindow(w);return 0;}if(m==WM_DESTROY){g_settings_window=NULL;if(g_main&&IsWindow(g_main)){EnableWindow(g_main,TRUE);SetForegroundWindow(g_main);}return 0;}return DefWindowProcW(w,m,wp,lp);
}

static void open_settings(HWND owner){WNDCLASSW wc;if(g_settings_window){ShowWindow(g_settings_window,SW_SHOW);SetForegroundWindow(g_settings_window);return;}ZeroMemory(&wc,sizeof(wc));wc.lpfnWndProc=SettingsProc;wc.hInstance=g_instance;wc.lpszClassName=L"BattleTechC64Settings";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);g_settings_window=CreateWindowExW(WS_EX_CONTROLPARENT,wc.lpszClassName,L"Settings",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,620,320,owner,NULL,g_instance,NULL);if(g_settings_window)EnableWindow(owner,FALSE);}

typedef struct AudioData{HWND enabled,volume,latency;}AudioData;
static LRESULT CALLBACK AudioProc(HWND w,UINT m,WPARAM wp,LPARAM lp){
 static AudioData d;static const int volumes[]={0,25,50,70,100},latencies[]={20,40,60,80,120,250};(void)lp;
 if(m==WM_CREATE){HWND heading,volume_label,latency_label,note,ok,cancel;const wchar_t*vitems[]={L"Muted",L"25%",L"50%",L"70%",L"100%"};const wchar_t*litems[]={L"20 ms",L"40 ms",L"60 ms",L"80 ms",L"120 ms",L"250 ms"};unsigned i;ZeroMemory(&d,sizeof(d));heading=CreateWindowW(L"STATIC",L"Audio output",WS_CHILD|WS_VISIBLE,18,14,260,22,w,NULL,g_instance,NULL);d.enabled=CreateWindowW(L"BUTTON",L"Enable &audio output",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX,18,42,260,28,w,NULL,g_instance,NULL);volume_label=CreateWindowW(L"STATIC",L"&Volume:",WS_CHILD|WS_VISIBLE,18,88,86,22,w,NULL,g_instance,NULL);d.volume=CreateWindowW(L"COMBOBOX",L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|CBS_DROPDOWNLIST,110,84,120,170,w,NULL,g_instance,NULL);for(i=0;i<COUNT_OF(vitems);i++)SendMessageW(d.volume,CB_ADDSTRING,0,(LPARAM)vitems[i]);latency_label=CreateWindowW(L"STATIC",L"&Latency:",WS_CHILD|WS_VISIBLE,18,128,86,22,w,NULL,g_instance,NULL);d.latency=CreateWindowW(L"COMBOBOX",L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|CBS_DROPDOWNLIST,110,124,120,190,w,NULL,g_instance,NULL);for(i=0;i<COUNT_OF(litems);i++)SendMessageW(d.latency,CB_ADDSTRING,0,(LPARAM)litems[i]);note=CreateWindowW(L"STATIC",L"Changes apply immediately to a running game.",WS_CHILD|WS_VISIBLE,18,170,390,24,w,NULL,g_instance,NULL);ok=CreateWindowW(L"BUTTON",L"OK",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,226,210,105,32,w,(HMENU)IDOK,g_instance,NULL);cancel=CreateWindowW(L"BUTTON",L"Cancel",WS_CHILD|WS_VISIBLE|WS_TABSTOP,349,210,105,32,w,(HMENU)IDCANCEL,g_instance,NULL);font(heading);font(d.enabled);font(volume_label);font(d.volume);font(latency_label);font(d.latency);font(note);font(ok);font(cancel);SendMessageW(d.enabled,BM_SETCHECK,g_audio_enabled?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(d.volume,CB_SETCURSEL,combo_index(volumes,COUNT_OF(volumes),g_volume),0);SendMessageW(d.latency,CB_SETCURSEL,combo_index(latencies,COUNT_OF(latencies),g_latency),0);SetFocus(d.enabled);return 0;}
 if(m==WM_COMMAND){if(LOWORD(wp)==IDOK){int v=(int)SendMessageW(d.volume,CB_GETCURSEL,0,0),l=(int)SendMessageW(d.latency,CB_GETCURSEL,0,0);g_audio_enabled=SendMessageW(d.enabled,BM_GETCHECK,0,0)==BST_CHECKED;if(v>=0&&v<(int)COUNT_OF(volumes))g_volume=volumes[v];if(l>=0&&l<(int)COUNT_OF(latencies))g_latency=latencies[l];save_settings();if(apply_live_audio_settings())status(L"Audio settings applied to the running game.");else status(g_game?L"Audio settings saved; the running game is not ready yet.":L"Audio settings saved for the next game.");DestroyWindow(w);return 0;}if(LOWORD(wp)==IDCANCEL){DestroyWindow(w);return 0;}}
 if((m==WM_KEYDOWN&&wp==VK_ESCAPE)||m==WM_CLOSE){DestroyWindow(w);return 0;}if(m==WM_DESTROY){g_audio_window=NULL;if(g_main&&IsWindow(g_main)){EnableWindow(g_main,TRUE);SetForegroundWindow(g_main);}return 0;}return DefWindowProcW(w,m,wp,lp);
}

static void open_audio(HWND owner){WNDCLASSW wc;if(g_audio_window){ShowWindow(g_audio_window,SW_SHOW);SetForegroundWindow(g_audio_window);return;}ZeroMemory(&wc,sizeof(wc));wc.lpfnWndProc=AudioProc;wc.hInstance=g_instance;wc.lpszClassName=L"BattleTechC64Audio";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);g_audio_window=CreateWindowExW(WS_EX_CONTROLPARENT,wc.lpszClassName,L"Audio",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,490,300,owner,NULL,g_instance,NULL);if(g_audio_window)EnableWindow(owner,FALSE);}

static const wchar_t*action_name(unsigned action){static const wchar_t*names[BINDING_COUNT]={L"Up",L"Down",L"Left",L"Right",L"Fire",L"C64 Space/Menu",L"C64 Return"};return action<BINDING_COUNT?names[action]:L"Unknown";}
static void key_name(UINT key,wchar_t*out,size_t count){UINT scan;if(key==VK_UP){wcsncpy(out,L"Up Arrow",count);return;}if(key==VK_DOWN){wcsncpy(out,L"Down Arrow",count);return;}if(key==VK_LEFT){wcsncpy(out,L"Left Arrow",count);return;}if(key==VK_RIGHT){wcsncpy(out,L"Right Arrow",count);return;}if(key==VK_SPACE){wcsncpy(out,L"Space",count);return;}if(key==VK_RETURN){wcsncpy(out,L"Enter",count);return;}if(key==VK_CONTROL){wcsncpy(out,L"Ctrl",count);return;}scan=MapVirtualKeyW(key,MAPVK_VK_TO_VSC);if(GetKeyNameTextW((LONG)(scan<<16),out,(int)count)<=0)_snwprintf(out,count,L"Key %u",key);out[count-1]=0;}
typedef struct ControlData{HWND button[BINDING_COUNT],source,deadzone;UINT pending[BINDING_COUNT];}ControlData;
static void binding_text(ControlData*d,unsigned action){wchar_t key[64],text[160];key_name(d->pending[action],key,COUNT_OF(key));_snwprintf(text,COUNT_OF(text),L"%s: %s",action_name(action),key);SetWindowTextW(d->button[action],text);}
static LRESULT CALLBACK ControlsProc(HWND w,UINT m,WPARAM wp,LPARAM lp){
 static ControlData d;const int base=5000;(void)lp;
 if(m==WM_CREATE){HWND source_label,deadzone_label,gamepad,heading,instructions,ok,cancel;const wchar_t*sources[]={L"Keyboard",L"Gamepad",L"Keyboard + gamepad"};const wchar_t*deadzones[]={L"20%",L"35%",L"50%",L"65%"};unsigned i;ZeroMemory(&d,sizeof(d));g_capture_action=-1;memcpy(d.pending,g_bindings,sizeof(g_bindings));source_label=CreateWindowW(L"STATIC",L"&Input source:",WS_CHILD|WS_VISIBLE,18,14,90,22,w,NULL,g_instance,NULL);d.source=CreateWindowW(L"COMBOBOX",L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|CBS_DROPDOWNLIST,110,10,205,120,w,(HMENU)4900,g_instance,NULL);for(i=0;i<COUNT_OF(sources);i++)SendMessageW(d.source,CB_ADDSTRING,0,(LPARAM)sources[i]);SendMessageW(d.source,CB_SETCURSEL,g_input_source,0);deadzone_label=CreateWindowW(L"STATIC",L"&Deadzone:",WS_CHILD|WS_VISIBLE,350,14,80,22,w,NULL,g_instance,NULL);d.deadzone=CreateWindowW(L"COMBOBOX",L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|CBS_DROPDOWNLIST,438,10,120,120,w,(HMENU)4901,g_instance,NULL);for(i=0;i<COUNT_OF(deadzones);i++)SendMessageW(d.deadzone,CB_ADDSTRING,0,(LPARAM)deadzones[i]);SendMessageW(d.deadzone,CB_SETCURSEL,g_deadzone<=20?0:g_deadzone<=35?1:g_deadzone<=50?2:3,0);gamepad=CreateWindowW(L"STATIC",L"Gamepad: D-pad or left stick moves; south face button fires; Start is C64 Space/menu. Controllers may be connected during play.",WS_CHILD|WS_VISIBLE,18,48,540,42,w,NULL,g_instance,NULL);heading=CreateWindowW(L"STATIC",L"C64 keyboard",WS_CHILD|WS_VISIBLE,18,96,540,24,w,NULL,g_instance,NULL);for(i=0;i<BINDING_COUNT;i++){d.button[i]=CreateWindowW(L"BUTTON",L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP,18,126+(int)i*38,540,30,w,(HMENU)(INT_PTR)(base+(int)i),g_instance,NULL);font(d.button[i]);binding_text(&d,i);}instructions=CreateWindowW(L"STATIC",L"Choose a keyboard control, then press its new key. Escape cancels capture. Launcher and gameplay shortcuts cannot be assigned.",WS_CHILD|WS_VISIBLE,18,400,540,42,w,NULL,g_instance,NULL);ok=CreateWindowW(L"BUTTON",L"OK",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,330,454,105,32,w,(HMENU)IDOK,g_instance,NULL);cancel=CreateWindowW(L"BUTTON",L"Cancel",WS_CHILD|WS_VISIBLE|WS_TABSTOP,453,454,105,32,w,(HMENU)IDCANCEL,g_instance,NULL);font(source_label);font(d.source);font(deadzone_label);font(d.deadzone);font(gamepad);font(heading);font(instructions);font(ok);font(cancel);SetFocus(d.source);return 0;}
 if(m==WM_COMMAND){int id=LOWORD(wp);if(id>=base&&id<base+BINDING_COUNT){g_capture_action=id-base;SetWindowTextW(d.button[g_capture_action],L"Press a key...");SetFocus(w);return 0;}if(id==IDOK){static const int deadzones[4]={20,35,50,65};int source=(int)SendMessageW(d.source,CB_GETCURSEL,0,0),deadzone=(int)SendMessageW(d.deadzone,CB_GETCURSEL,0,0);if(source>=0&&source<=2)g_input_source=source;if(deadzone>=0&&deadzone<4)g_deadzone=deadzones[deadzone];memcpy(g_bindings,d.pending,sizeof(g_bindings));save_settings();status(L"Controls saved. They apply when gameplay next starts.");DestroyWindow(w);return 0;}if(id==IDCANCEL){DestroyWindow(w);return 0;}}
 if(m==WM_KEYDOWN&&g_capture_action>=0){UINT key=(UINT)wp;unsigned i;if(key==VK_ESCAPE){binding_text(&d,(unsigned)g_capture_action);g_capture_action=-1;return 0;}if(!valid_binding(key)){MessageBeep(MB_ICONWARNING);return 0;}for(i=0;i<BINDING_COUNT;i++)if((int)i!=g_capture_action&&d.pending[i]==key){d.pending[i]=d.pending[g_capture_action];binding_text(&d,i);}d.pending[g_capture_action]=key;binding_text(&d,(unsigned)g_capture_action);g_capture_action=-1;return 0;}
 if((m==WM_KEYDOWN&&wp==VK_ESCAPE)||m==WM_CLOSE){DestroyWindow(w);return 0;}if(m==WM_DESTROY){g_capture_action=-1;g_controls_window=NULL;if(g_main&&IsWindow(g_main)){EnableWindow(g_main,TRUE);SetForegroundWindow(g_main);}return 0;}return DefWindowProcW(w,m,wp,lp);
}

static void open_controls(HWND owner){WNDCLASSW wc;if(g_controls_window){ShowWindow(g_controls_window,SW_SHOW);SetForegroundWindow(g_controls_window);return;}ZeroMemory(&wc,sizeof(wc));wc.lpfnWndProc=ControlsProc;wc.hInstance=g_instance;wc.lpszClassName=L"BattleTechC64Controls";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);g_controls_window=CreateWindowExW(WS_EX_CONTROLPARENT,wc.lpszClassName,L"Controls",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,590,550,owner,NULL,g_instance,NULL);if(g_controls_window)EnableWindow(owner,FALSE);}

static BOOL CALLBACK find_game_window(HWND w,LPARAM value){DWORD pid=0;wchar_t title[256];GetWindowThreadProcessId(w,&pid);if(pid!=(DWORD)value||GetWindow(w,GW_OWNER)!=NULL)return TRUE;GetWindowTextW(w,title,COUNT_OF(title));if(!wcscmp(title,GAME_TITLE)){g_game_window=w;return FALSE;}return TRUE;}
static void close_event(HANDLE*event){if(*event){CloseHandle(*event);*event=NULL;}}
static void close_game_events(void){close_event(&g_resume_event);close_event(&g_save_event);close_event(&g_load_event);close_event(&g_capture_event);close_event(&g_audio_event);close_event(&g_audio_mapping);}
static HANDLE open_game_event(const wchar_t*kind){wchar_t name[128];_snwprintf(name,COUNT_OF(name),L"Local\\BattleTechC64%s-%lu",kind,(unsigned long)g_game_pid);return OpenEventW(EVENT_MODIFY_STATE,FALSE,name);}
static HANDLE open_game_mapping(const wchar_t*kind){wchar_t name[128];_snwprintf(name,COUNT_OF(name),L"Local\\BattleTechC64%s-%lu",kind,(unsigned long)g_game_pid);return OpenFileMappingW(FILE_MAP_READ|FILE_MAP_WRITE,FALSE,name);}
static void update_controls(void);

static void show_game_failure(DWORD exit_code){HANDLE file;LARGE_INTEGER size,pos;char bytes[6001];DWORD got=0;wchar_t details[6001],message[7000];details[0]=0;file=CreateFileW(g_log_path,GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);if(file!=INVALID_HANDLE_VALUE){if(GetFileSizeEx(file,&size)){pos.QuadPart=size.QuadPart>(LONGLONG)(sizeof(bytes)-1u)?size.QuadPart-(LONGLONG)(sizeof(bytes)-1u):0;SetFilePointerEx(file,pos,NULL,FILE_BEGIN);if(ReadFile(file,bytes,sizeof(bytes)-1u,&got,NULL)){bytes[got]=0;if(MultiByteToWideChar(CP_UTF8,0,bytes,-1,details,COUNT_OF(details))<=0)details[0]=0;}}CloseHandle(file);}if(details[0])_snwprintf(message,COUNT_OF(message),L"The game stopped with error code %lu.\r\n\r\n%s\r\n\r\nFull log: %s",(unsigned long)exit_code,details,g_log_path);else _snwprintf(message,COUNT_OF(message),L"The game stopped with error code %lu.\r\n\r\nNo error details could be read. Full log: %s",(unsigned long)exit_code,g_log_path);message[COUNT_OF(message)-1]=0;MessageBoxW(g_main,message,L"BattleTech C64 error",MB_OK|MB_ICONERROR);}

static void refresh_game_connection(void){int changed=0;if(!g_game_window){EnumWindows(find_game_window,(LPARAM)g_game_pid);if(g_game_window)changed=1;}if(g_game_window){if(!g_resume_event){g_resume_event=open_game_event(L"Resume");if(g_resume_event)changed=1;}if(!g_save_event){g_save_event=open_game_event(L"Save");if(g_save_event)changed=1;}if(!g_load_event){g_load_event=open_game_event(L"Load");if(g_load_event)changed=1;}if(!g_capture_event){g_capture_event=open_game_event(L"Capture");if(g_capture_event)changed=1;}if(!g_audio_event){g_audio_event=open_game_event(L"Audio");if(g_audio_event)changed=1;}if(!g_audio_mapping){g_audio_mapping=open_game_mapping(L"AudioConfig");if(g_audio_mapping)changed=1;}if(!g_game_connected&&g_resume_event&&g_save_event&&g_load_event&&g_capture_event&&g_audio_event&&g_audio_mapping){g_game_connected=1;changed=1;if(!g_paused){ShowWindow(g_main,SW_HIDE);status(L"Game running. Press Escape to return to Launcher.");}}}if(changed)update_controls();}

static int apply_live_audio_settings(void){bt_frontend_audio_config*config;if(!g_game||!g_audio_event||!g_audio_mapping)return 0;config=(bt_frontend_audio_config*)MapViewOfFile(g_audio_mapping,FILE_MAP_READ|FILE_MAP_WRITE,0,0,sizeof(*config));if(!config)return 0;InterlockedExchange(&config->enabled,g_audio_enabled?1:0);InterlockedExchange(&config->volume,g_volume);InterlockedExchange(&config->latency_ms,g_latency);MemoryBarrier();UnmapViewOfFile(config);return SetEvent(g_audio_event)!=0;}

static void focus_game_window(void){DWORD game_thread,current_thread;BOOL attached=FALSE;if(!g_game_window||!IsWindow(g_game_window))return;AllowSetForegroundWindow(g_game_pid);ShowWindow(g_game_window,SW_SHOW);game_thread=GetWindowThreadProcessId(g_game_window,NULL);current_thread=GetCurrentThreadId();if(game_thread&&game_thread!=current_thread)attached=AttachThreadInput(current_thread,game_thread,TRUE);BringWindowToTop(g_game_window);SetForegroundWindow(g_game_window);SetActiveWindow(g_game_window);SetFocus(g_game_window);if(attached)AttachThreadInput(current_thread,game_thread,FALSE);}

static void update_controls(void){
 int running=g_game!=NULL,can_play=running&&g_paused&&g_resume_event;SetWindowTextW(g_browse,g_media_ready?L"&Run":L"&Browse");SetWindowTextW(g_play,L"&Play");EnableWindow(g_browse,!running);EnableWindow(g_play,can_play);EnableWindow(g_reset,running);EnableWindow(g_fullscreen,TRUE);SendMessageW(g_fullscreen,BM_SETCHECK,g_fullscreen_setting?BST_CHECKED:BST_UNCHECKED,0);SendMessageW(g_autorun,BM_SETCHECK,g_auto_run?BST_CHECKED:BST_UNCHECKED,0);
 EnableMenuItem(g_menu,CMD_BROWSE,MF_BYCOMMAND|(running?MF_GRAYED:MF_ENABLED));EnableMenuItem(g_menu,CMD_RUN,MF_BYCOMMAND|(!running&&g_media_ready?MF_ENABLED:MF_GRAYED));EnableMenuItem(g_menu,CMD_PLAY,MF_BYCOMMAND|(can_play?MF_ENABLED:MF_GRAYED));EnableMenuItem(g_menu,CMD_RESET,MF_BYCOMMAND|(running?MF_ENABLED:MF_GRAYED));EnableMenuItem(g_menu,CMD_SAVE,MF_BYCOMMAND|(g_save_event?MF_ENABLED:MF_GRAYED));EnableMenuItem(g_menu,CMD_LOAD,MF_BYCOMMAND|(g_load_event?MF_ENABLED:MF_GRAYED));EnableMenuItem(g_menu,CMD_SCREENSHOT,MF_BYCOMMAND|(g_capture_event?MF_ENABLED:MF_GRAYED));CheckMenuItem(g_menu,CMD_FULLSCREEN,MF_BYCOMMAND|(g_fullscreen_setting?MF_CHECKED:MF_UNCHECKED));CheckMenuItem(g_menu,CMD_AUTORUN,MF_BYCOMMAND|(g_auto_run?MF_CHECKED:MF_UNCHECKED));DrawMenuBar(g_main);
}

static void resume_game(void){if(!g_game||!g_paused||!g_resume_event||!g_game_window)return;AllowSetForegroundWindow(g_game_pid);if(SetEvent(g_resume_event)){g_paused=0;focus_game_window();ShowWindow(g_main,SW_HIDE);status(L"Game resumed. Press Escape in the game to return to Launcher.");update_controls();}}
static void signal_game(HANDLE event,const wchar_t*message){if(event&&SetEvent(event))status(message);else status(L"That game command is not available yet.");}

static int launch_game(void){
 wchar_t game[32768],system[32768],saves[32768],shots[32768],basic[32768],kernal[32768],chargen[32768],drive[32768],d0[32768],d1[32768],command[32768];STARTUPINFOW si;PROCESS_INFORMATION pi;SECURITY_ATTRIBUTES security;HANDLE log=INVALID_HANDLE_VALUE,input=INVALID_HANDLE_VALUE;int command_length;
 if(!g_media_ready)return 0;
 if(media_pair_status(g_media_directory)!=1){g_media_ready=0;status(L"The selected BattleTech disk images are missing or invalid. Browse for the verified pair.");update_controls();MessageBoxW(g_main,L"The selected disk images changed or are not the verified BattleTech C64 media.",L"Play",MB_OK|MB_ICONERROR);return 0;}
 if(!GetModuleFileNameW(NULL,game,COUNT_OF(game))||!join_path(system,COUNT_OF(system),g_directory,L"System")||!join_path(saves,COUNT_OF(saves),g_directory,L"Saves")||!join_path(shots,COUNT_OF(shots),g_directory,L"Screenshots")||!join_path(basic,COUNT_OF(basic),system,L"basic-901226-01.bin")||!join_path(kernal,COUNT_OF(kernal),system,L"kernal-901227-03.bin")||!join_path(chargen,COUNT_OF(chargen),system,L"chargen-901225-01.bin")||!join_path(drive,COUNT_OF(drive),system,L"dos1541ii-251968-03.bin")||!join_path(d0,COUNT_OF(d0),g_media_directory,L"BATTLET0.D64")||!join_path(d1,COUNT_OF(d1),g_media_directory,L"BATTLET1.D64")||!join_path(g_log_path,COUNT_OF(g_log_path),g_directory,L"frontend.log")){MessageBoxW(g_main,L"The installation or media path is too long for Windows.",L"Play",MB_OK|MB_ICONERROR);return 0;}CreateDirectoryW(saves,NULL);CreateDirectoryW(shots,NULL);
 if(!file_exists(game)||!file_exists(basic)||!file_exists(kernal)||!file_exists(chargen)||!file_exists(drive)||!file_exists(d0)||!file_exists(d1)){MessageBoxW(g_main,L"A required game, system ROM, or disk file is missing.",L"BattleTech C64 media",MB_OK|MB_ICONERROR);return 0;}
 command_length=_snwprintf(command,COUNT_OF(command),L"\"%s\" --game --basic \"%s\" --kernal \"%s\" --chargen \"%s\" --drive-rom \"%s\" --disk1 \"%s\" --disk2 \"%s\" --save-dir \"%s\" --screenshot-dir \"%s\" --launcher-hwnd %llu --scale %d --volume %d --audio-latency %d --input-source %d --deadzone %d --key-up %u --key-down %u --key-left %u --key-right %u --key-fire %u --key-space %u --key-return %u%s%s%s%s%s",game,basic,kernal,chargen,drive,d0,d1,saves,shots,(unsigned long long)(uintptr_t)g_main,g_scale,g_volume,g_latency,g_input_source,g_deadzone,g_bindings[0],g_bindings[1],g_bindings[2],g_bindings[3],g_bindings[4],g_bindings[5],g_bindings[6],g_audio_enabled?L"":L" --mute",g_fullscreen_setting?L" --fullscreen":L"",g_correct_aspect?L" --correct-aspect":L"",g_vsync?L" --vsync":L"",g_pause_focus?L" --pause-on-focus-loss":L"");if(command_length<0||(size_t)command_length>=COUNT_OF(command)){MessageBoxW(g_main,L"The generated game command is too long for Windows.",L"Play",MB_OK|MB_ICONERROR);return 0;}
 ZeroMemory(&security,sizeof(security));security.nLength=sizeof(security);security.bInheritHandle=TRUE;log=CreateFileW(g_log_path,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,&security,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,NULL);input=CreateFileW(L"NUL",GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE,&security,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);if(log==INVALID_HANDLE_VALUE||input==INVALID_HANDLE_VALUE){if(log!=INVALID_HANDLE_VALUE)CloseHandle(log);if(input!=INVALID_HANDLE_VALUE)CloseHandle(input);MessageBoxW(g_main,L"Windows could not create the frontend log file.",L"Play",MB_OK|MB_ICONERROR);return 0;}
 ZeroMemory(&si,sizeof(si));ZeroMemory(&pi,sizeof(pi));si.cb=sizeof(si);si.dwFlags=STARTF_USESTDHANDLES;si.hStdInput=input;si.hStdOutput=log;si.hStdError=log;if(!CreateProcessW(game,command,NULL,NULL,TRUE,CREATE_NO_WINDOW,NULL,g_directory,&si,&pi)){CloseHandle(log);CloseHandle(input);MessageBoxW(g_main,L"Windows could not start the BattleTech static-core frontend.",L"Play",MB_OK|MB_ICONERROR);return 0;}CloseHandle(log);CloseHandle(input);CloseHandle(pi.hThread);g_game=pi.hProcess;g_game_pid=pi.dwProcessId;g_game_window=NULL;g_game_connected=0;g_force_close_at=0;close_game_events();g_paused=0;status(L"BattleTech C64 is starting. Press Escape to return to Launcher.");SetTimer(g_main,TIMER_GAME,100,NULL);update_controls();return 1;
}

static void reset_game(void){if(!g_game)return;g_pending_restart=1;status(L"Resetting BattleTech C64 from frame zero.");if(g_game_window&&PostMessageW(g_game_window,WM_CLOSE,0,0))g_force_close_at=GetTickCount64()+3000u;else TerminateProcess(g_game,0);}
static void open_save_folder(void){wchar_t path[32768];if(!join_path(path,COUNT_OF(path),g_directory,L"Saves")){MessageBoxW(g_main,L"The save-folder path is too long.",L"Launcher",MB_OK|MB_ICONERROR);return;}CreateDirectoryW(path,NULL);if((INT_PTR)ShellExecuteW(g_main,L"open",path,NULL,NULL,SW_SHOWNORMAL)<=32)MessageBoxW(g_main,L"Windows could not open the save folder.",L"Launcher",MB_OK|MB_ICONERROR);}

static void layout(HWND w){RECT r;int width,height;GetClientRect(w,&r);width=r.right>0?r.right:1;height=r.bottom>0?r.bottom:1;MoveWindow(g_browse,8,8,92,30,TRUE);MoveWindow(g_play,106,8,72,30,TRUE);MoveWindow(g_reset,184,8,66,30,TRUE);MoveWindow(g_audio,256,8,66,30,TRUE);MoveWindow(g_settings_button,328,8,82,30,TRUE);MoveWindow(g_controls_button,416,8,84,30,TRUE);MoveWindow(g_fullscreen,510,10,112,26,TRUE);MoveWindow(g_autorun,632,10,100,26,TRUE);MoveWindow(g_status,12,48,width>24?width-24:1,24,TRUE);MoveWindow(g_video,0,80,width,height>80?height-80:1,TRUE);}

static HMENU make_menu(void){HMENU bar=CreateMenu(),file=CreatePopupMenu(),settings=CreatePopupMenu();AppendMenuW(file,MF_STRING,CMD_BROWSE,L"&Browse media...");AppendMenuW(file,MF_STRING,CMD_RUN,L"&Run\tF7");AppendMenuW(file,MF_STRING,CMD_PLAY,L"&Play\tEscape");AppendMenuW(file,MF_STRING,CMD_RESET,L"&Reset game");AppendMenuW(file,MF_SEPARATOR,0,NULL);AppendMenuW(file,MF_STRING,CMD_SAVE,L"Save Snapshot\tF2");AppendMenuW(file,MF_STRING,CMD_LOAD,L"Load Snapshot\tF3");AppendMenuW(file,MF_STRING,CMD_SCREENSHOT,L"Capture Game Frame\tF8");AppendMenuW(file,MF_STRING,CMD_SAVE_FOLDER,L"Open Save Folder");AppendMenuW(file,MF_SEPARATOR,0,NULL);AppendMenuW(file,MF_STRING,CMD_EXIT,L"E&xit\tAlt+F4");AppendMenuW(settings,MF_STRING,CMD_SETTINGS,L"&Settings...\tF4");AppendMenuW(settings,MF_STRING,CMD_CONTROLS,L"&Controls...\tF5");AppendMenuW(settings,MF_STRING,CMD_AUDIO,L"&Audio...\tF6");AppendMenuW(settings,MF_SEPARATOR,0,NULL);AppendMenuW(settings,MF_STRING,CMD_FULLSCREEN,L"Use &Full Screen When Playing");AppendMenuW(settings,MF_STRING,CMD_AUTORUN,L"&Auto-Run at Startup");AppendMenuW(settings,MF_SEPARATOR,0,NULL);AppendMenuW(settings,MF_STRING,CMD_GUIDE,L"Controls &Guide\tF1");AppendMenuW(settings,MF_STRING,CMD_ABOUT,L"&About");AppendMenuW(bar,MF_POPUP,(UINT_PTR)file,L"&File");AppendMenuW(bar,MF_POPUP,(UINT_PTR)settings,L"&Settings");return bar;}

static LRESULT CALLBACK MainProc(HWND w,UINT m,WPARAM wp,LPARAM lp){switch(m){
 case WM_CREATE:{HWND controls[9];unsigned i;g_main=w;g_video=CreateWindowExW(WS_EX_NOACTIVATE,L"STATIC",L"",WS_CHILD|WS_VISIBLE|WS_DISABLED|SS_BLACKRECT,0,80,1,1,w,NULL,g_instance,NULL);g_browse=CreateWindowW(L"BUTTON",L"&Browse",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_DEFPUSHBUTTON,8,8,92,30,w,(HMENU)TOOL_BROWSE,g_instance,NULL);g_play=CreateWindowW(L"BUTTON",L"&Play",WS_CHILD|WS_VISIBLE|WS_TABSTOP,106,8,72,30,w,(HMENU)TOOL_PLAY,g_instance,NULL);g_reset=CreateWindowW(L"BUTTON",L"&Reset",WS_CHILD|WS_VISIBLE|WS_TABSTOP,184,8,66,30,w,(HMENU)TOOL_RESET,g_instance,NULL);g_audio=CreateWindowW(L"BUTTON",L"&Audio",WS_CHILD|WS_VISIBLE|WS_TABSTOP,256,8,66,30,w,(HMENU)TOOL_AUDIO,g_instance,NULL);g_settings_button=CreateWindowW(L"BUTTON",L"&Settings",WS_CHILD|WS_VISIBLE|WS_TABSTOP,328,8,82,30,w,(HMENU)TOOL_SETTINGS,g_instance,NULL);g_controls_button=CreateWindowW(L"BUTTON",L"&Controls",WS_CHILD|WS_VISIBLE|WS_TABSTOP,416,8,84,30,w,(HMENU)TOOL_CONTROLS,g_instance,NULL);g_fullscreen=CreateWindowW(L"BUTTON",L"&Full screen",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX,510,10,112,26,w,(HMENU)TOOL_FULLSCREEN,g_instance,NULL);g_autorun=CreateWindowW(L"BUTTON",L"Auto-&Run",WS_CHILD|WS_VISIBLE|WS_TABSTOP|BS_AUTOCHECKBOX,632,10,100,26,w,(HMENU)TOOL_AUTORUN,g_instance,NULL);g_status=CreateWindowW(L"STATIC",L"Place both BattleTech D64 images in the portable Rom folder.",WS_CHILD|WS_VISIBLE|SS_LEFT|SS_NOPREFIX,12,48,800,24,w,NULL,g_instance,NULL);controls[0]=g_browse;controls[1]=g_play;controls[2]=g_reset;controls[3]=g_audio;controls[4]=g_settings_button;controls[5]=g_controls_button;controls[6]=g_fullscreen;controls[7]=g_autorun;controls[8]=g_status;for(i=0;i<COUNT_OF(controls);i++)font(controls[i]);update_controls();return 0;}
 case WM_SIZE:layout(w);return 0;case WM_GETMINMAXINFO:((MINMAXINFO*)lp)->ptMinTrackSize.x=760;((MINMAXINFO*)lp)->ptMinTrackSize.y=580;return 0;
 case WM_COMMAND:{unsigned id=LOWORD(wp);if(id==CMD_BROWSE||(id==TOOL_BROWSE&&!g_media_ready)){select_media();update_controls();return 0;}if(id==CMD_RUN||(id==TOOL_BROWSE&&g_media_ready)){if(!g_game)launch_game();return 0;}if(id==CMD_PLAY||id==TOOL_PLAY){resume_game();return 0;}if(id==CMD_RESET||id==TOOL_RESET){reset_game();return 0;}if(id==CMD_AUDIO||id==TOOL_AUDIO){open_audio(w);return 0;}if(id==CMD_SETTINGS||id==TOOL_SETTINGS){open_settings(w);return 0;}if(id==CMD_CONTROLS||id==TOOL_CONTROLS){open_controls(w);return 0;}if(id==CMD_FULLSCREEN||id==TOOL_FULLSCREEN){if(id==CMD_FULLSCREEN)SendMessageW(g_fullscreen,BM_SETCHECK,SendMessageW(g_fullscreen,BM_GETCHECK,0,0)==BST_CHECKED?BST_UNCHECKED:BST_CHECKED,0);g_fullscreen_setting=SendMessageW(g_fullscreen,BM_GETCHECK,0,0)==BST_CHECKED;save_settings();update_controls();return 0;}if(id==CMD_AUTORUN||id==TOOL_AUTORUN){if(id==CMD_AUTORUN)SendMessageW(g_autorun,BM_SETCHECK,SendMessageW(g_autorun,BM_GETCHECK,0,0)==BST_CHECKED?BST_UNCHECKED:BST_CHECKED,0);g_auto_run=SendMessageW(g_autorun,BM_GETCHECK,0,0)==BST_CHECKED;save_settings();status(g_auto_run?L"Auto-Run enabled.":L"Auto-Run disabled.");update_controls();return 0;}if(id==CMD_SAVE){signal_game(g_save_event,L"Snapshot save requested.");return 0;}if(id==CMD_LOAD){signal_game(g_load_event,L"Snapshot load requested.");return 0;}if(id==CMD_SCREENSHOT){signal_game(g_capture_event,L"Game-frame capture requested.");return 0;}if(id==CMD_SAVE_FOLDER){open_save_folder();return 0;}if(id==CMD_GUIDE){show_guide(w);return 0;}if(id==CMD_ABOUT){show_information(w,L"About",L"BattleTech: The Crescent Hawk's Inception\r\nCommodore 64 Static Recompilation\r\n\r\nOfficial recomp version " BT_RECOMP_VERSION_W L"\r\nMedia: BATTLET0.D64 and BATTLET1.D64\r\nPlatform: Commodore 64\r\n\r\nNative Windows frontend using the static core. No VICE process or interpreter fallback is used.",540,360);return 0;}if(id==CMD_EXIT){SendMessageW(w,WM_CLOSE,0,0);return 0;}break;}
 case WM_KEYDOWN:if(wp==VK_ESCAPE){resume_game();return 0;}if(wp==VK_F1){show_guide(w);return 0;}if(wp==VK_F2){SendMessageW(w,WM_COMMAND,CMD_SAVE,0);return 0;}if(wp==VK_F3){SendMessageW(w,WM_COMMAND,CMD_LOAD,0);return 0;}if(wp==VK_F4){open_settings(w);return 0;}if(wp==VK_F5){open_controls(w);return 0;}if(wp==VK_F6){open_audio(w);return 0;}if(wp==VK_F7){if(!g_game&&g_media_ready)launch_game();return 0;}if(wp==VK_F8){SendMessageW(w,WM_COMMAND,CMD_SCREENSHOT,0);return 0;}break;
 case WM_GAME_RETURN:g_paused=1;ShowWindow(w,SW_RESTORE);SetForegroundWindow(w);SetFocus(g_play);NotifyWinEvent(EVENT_OBJECT_FOCUS,g_play,OBJID_CLIENT,CHILDID_SELF);status(L"Paused. Choose Play or press Escape to continue.");update_controls();return 0;
 case WM_TIMER:if(wp==TIMER_GAME&&g_game){DWORD wait,exit_code=0;if(g_force_close_at&&GetTickCount64()>=g_force_close_at){TerminateProcess(g_game,0);g_force_close_at=0;}wait=WaitForSingleObject(g_game,0);if(wait==WAIT_OBJECT_0){GetExitCodeProcess(g_game,&exit_code);CloseHandle(g_game);g_game=NULL;KillTimer(w,TIMER_GAME);g_game_pid=0;g_game_window=NULL;g_game_connected=0;g_force_close_at=0;g_paused=0;close_game_events();if(g_pending_exit){DestroyWindow(w);return 0;}if(g_pending_restart){g_pending_restart=0;launch_game();return 0;}status(exit_code?L"The game stopped with an error.":L"Game closed. Original D64 files remain unchanged.");update_controls();ShowWindow(w,SW_RESTORE);SetForegroundWindow(w);if(exit_code)show_game_failure(exit_code);return 0;}refresh_game_connection();}return 0;
 case WM_CLOSE:if(g_game){if(MessageBoxW(w,L"The game is still running. Exit both the game and Launcher?",L"Launcher",MB_YESNO|MB_ICONQUESTION)!=IDYES)return 0;g_pending_exit=1;if(g_game_window&&PostMessageW(g_game_window,WM_CLOSE,0,0))g_force_close_at=GetTickCount64()+3000u;else TerminateProcess(g_game,0);return 0;}DestroyWindow(w);return 0;
 case WM_DESTROY:KillTimer(w,TIMER_GAME);close_game_events();PostQuitMessage(0);return 0;default:break;}return DefWindowProcW(w,m,wp,lp);}

int WINAPI wWinMain(HINSTANCE instance,HINSTANCE previous,LPWSTR command_line,int show){wchar_t module[32768],*slash;WNDCLASSW wc;HWND w;MSG msg;int message_result;(void)previous;(void)command_line;(void)show;g_instance=instance;if(!GetModuleFileNameW(NULL,module,COUNT_OF(module)))return 1;slash=wcsrchr(module,L'\\');if(!slash)return 1;*slash=0;wcsncpy(g_directory,module,COUNT_OF(g_directory)-1);g_directory[COUNT_OF(g_directory)-1]=0;if(!join_path(g_ini_path,COUNT_OF(g_ini_path),g_directory,L"settings.ini"))return 1;load_settings();GetPrivateProfileStringW(L"Frontend",L"RomFolder",L"",g_media_directory,COUNT_OF(g_media_directory),g_ini_path);if(media_pair_status(g_media_directory)!=1)join_path(g_media_directory,COUNT_OF(g_media_directory),g_directory,L"Rom");g_media_ready=media_pair_status(g_media_directory)==1;if(!GetPrivateProfileIntW(L"Frontend",L"WelcomeShown",0,g_ini_path)){show_welcome();if(g_info_window){while(g_info_window&&(message_result=GetMessageW(&msg,NULL,0,0))>0){if(g_info_window&&IsDialogMessageW(g_info_window,&msg))continue;TranslateMessage(&msg);DispatchMessageW(&msg);}if(message_result<=0)return message_result<0?1:(int)msg.wParam;WritePrivateProfileStringW(L"Frontend",L"WelcomeShown",L"1",g_ini_path);}}g_menu=make_menu();ZeroMemory(&wc,sizeof(wc));wc.lpfnWndProc=MainProc;wc.hInstance=instance;wc.lpszClassName=L"BattleTechC64ModernLauncher";wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.hIcon=LoadIcon(NULL,IDI_APPLICATION);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);if(!RegisterClassW(&wc)&&GetLastError()!=ERROR_CLASS_ALREADY_EXISTS)return 1;w=CreateWindowExW(WS_EX_CONTROLPARENT,wc.lpszClassName,L"Launcher",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1024,820,NULL,g_menu,instance,NULL);if(!w)return 1;ShowWindow(w,SW_SHOWNORMAL);UpdateWindow(w);BringWindowToTop(w);SetForegroundWindow(w);SetFocus(g_browse);status(g_media_ready?L"Both verified BattleTech disk images are ready. Select Run or press F7.":L"Place the verified BATTLET0.D64 and BATTLET1.D64 files in the portable Rom folder.");update_controls();if(g_media_ready&&g_auto_run)PostMessageW(w,WM_COMMAND,CMD_RUN,0);
 while(GetMessageW(&msg,NULL,0,0)>0){if(g_controls_window&&g_capture_action>=0&&msg.message==WM_KEYDOWN){SendMessageW(g_controls_window,msg.message,msg.wParam,msg.lParam);continue;}if(g_info_window&&IsDialogMessageW(g_info_window,&msg))continue;if(g_settings_window&&IsDialogMessageW(g_settings_window,&msg))continue;if(g_audio_window&&IsDialogMessageW(g_audio_window,&msg))continue;if(g_controls_window&&IsDialogMessageW(g_controls_window,&msg))continue;if(IsWindowEnabled(w)&&msg.message==WM_KEYDOWN&&frontend_key((UINT)msg.wParam)){SendMessageW(w,msg.message,msg.wParam,msg.lParam);continue;}if(!IsDialogMessageW(w,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}}return (int)msg.wParam;}
