#include "../public/bt_static_core_internal.h"
#include "../media/bt_sha256.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#define SNAP_MAGIC "BTC11SN1"
#define SNAP_HEADER_BYTES 320u
#define SNAP_ENDIAN_MARKER 0x12345678u
static const char *PROFILE_SHA="7afef179af01cf16c67d07ca8d20ed31f39112fb1f9b72b38bf8c300ff1e9de6";
typedef struct W{uint8_t*p;size_t cap,pos;int ok;}W;typedef struct R{const uint8_t*p;size_t n,pos;int ok;}R;
static void wb(W*w,const void*p,size_t n){if(!w->ok)return;if(w->p&&w->pos+n>w->cap){w->ok=0;return;}if(w->p)memcpy(w->p+w->pos,p,n);w->pos+=n;}static void w8(W*w,uint8_t v){wb(w,&v,1);}static void w16(W*w,uint16_t v){uint8_t b[2]={(uint8_t)v,(uint8_t)(v>>8)};wb(w,b,2);}static void w32(W*w,uint32_t v){uint8_t b[4]={(uint8_t)v,(uint8_t)(v>>8),(uint8_t)(v>>16),(uint8_t)(v>>24)};wb(w,b,4);}static void w64(W*w,uint64_t v){unsigned i;for(i=0;i<8;i++)w8(w,(uint8_t)(v>>(8u*i)));}
static void rb(R*r,void*p,size_t n){if(!r->ok||r->pos+n>r->n){r->ok=0;return;}memcpy(p,r->p+r->pos,n);r->pos+=n;}static uint8_t r8(R*r){uint8_t v=0;rb(r,&v,1);return v;}static uint16_t r16(R*r){uint16_t v=r8(r);v|=(uint16_t)r8(r)<<8;return v;}static uint32_t r32(R*r){uint32_t v=r16(r);v|=(uint32_t)r16(r)<<16;return v;}static uint64_t r64(R*r){uint64_t v=0;unsigned i;for(i=0;i<8;i++)v|=(uint64_t)r8(r)<<(8u*i);return v;}
static unsigned hex_nibble(char value){
    if(value>='0'&&value<='9')return (unsigned)(value-'0');
    if(value>='a'&&value<='f')return (unsigned)(value-'a')+10u;
    return 99u;
}
static int hex32(const char*s,uint8_t o[32]){unsigned i;for(i=0;i<32;i++){unsigned a=hex_nibble(s[i*2]),b=hex_nibble(s[i*2+1]);if(a>15u||b>15u)return 0;o[i]=(uint8_t)((a<<4)|b);}return 1;}
static void enc_cpu(W*w,const cpu6510*c){w16(w,c->pc);w8(w,c->a);w8(w,c->x);w8(w,c->y);w8(w,c->sp);w8(w,c->p);w64(w,c->cycles);w8(w,(uint8_t)c->jammed);w8(w,(uint8_t)c->irq_line);w8(w,(uint8_t)c->nmi_line);w8(w,(uint8_t)c->nmi_edge_pending);w8(w,(uint8_t)c->irq_sampled);w8(w,c->xaa_magic);w8(w,c->lxa_magic);}static void dec_cpu(R*r,cpu6510*c){c->pc=r16(r);c->a=r8(r);c->x=r8(r);c->y=r8(r);c->sp=r8(r);c->p=r8(r);c->cycles=r64(r);c->jammed=r8(r)!=0;c->irq_line=r8(r)!=0;c->nmi_line=r8(r)!=0;c->nmi_edge_pending=r8(r)!=0;c->irq_sampled=r8(r)!=0;c->xaa_magic=r8(r);c->lxa_magic=r8(r);}
static void enc_bus(W*w,const c64_bus*b){wb(w,b->ram,sizeof(b->ram));wb(w,b->color_ram,sizeof(b->color_ram));w8(w,b->cpu_port_ddr);w8(w,b->cpu_port_data);w8(w,b->cpu_port_data_out);w8(w,b->cpu_port_cap_67);w64(w,b->cpu_port_cap_deadline_6);w64(w,b->cpu_port_cap_deadline_7);w32(w,b->cpu_port_falloff_cycles);w64(w,b->cpu_cycle);w8(w,(uint8_t)b->game_high);w8(w,(uint8_t)b->exrom_high);w8(w,b->vic_phi1_bus);w8(w,b->cia2_pra);w8(w,b->cia2_ddra);w8(w,b->vic_bank);}static void dec_bus(R*r,c64_bus*b){rb(r,b->ram,sizeof(b->ram));rb(r,b->color_ram,sizeof(b->color_ram));b->cpu_port_ddr=r8(r);b->cpu_port_data=r8(r);b->cpu_port_data_out=r8(r);b->cpu_port_cap_67=r8(r);b->cpu_port_cap_deadline_6=r64(r);b->cpu_port_cap_deadline_7=r64(r);b->cpu_port_falloff_cycles=r32(r);b->cpu_cycle=r64(r);b->game_high=r8(r)!=0;b->exrom_high=r8(r)!=0;b->vic_phi1_bus=r8(r);b->cia2_pra=r8(r);b->cia2_ddra=r8(r);b->vic_bank=r8(r);}
static void enc_sched(W*w,const bt_scheduler*s){size_t i,n=0;w64(w,s->cycle);w64(w,s->next_sequence);w8(w,s->failed);for(i=0;i<BT_SCHEDULER_MAX_EVENTS;i++)if(s->events[i].active)n++;w32(w,(uint32_t)n);for(i=0;i<BT_SCHEDULER_MAX_EVENTS;i++)if(s->events[i].active){const bt_scheduler_event*e=&s->events[i];w64(w,e->cycle);w64(w,e->sequence);w64(w,e->value);w32(w,e->type);w16(w,e->priority);}}
static void dec_sched(R*r,bt_scheduler*s){uint32_t i,n;s->cycle=r64(r);s->next_sequence=r64(r);s->failed=r8(r);memset(s->events,0,sizeof(s->events));n=r32(r);if(n>BT_SCHEDULER_MAX_EVENTS){r->ok=0;return;}for(i=0;i<n;i++){bt_scheduler_event*e=&s->events[i];e->cycle=r64(r);e->sequence=r64(r);e->value=r64(r);e->type=r32(r);e->priority=r16(r);e->active=1u;}}
static void enc_timer(W*w,const cia6526_timer*t){w16(w,t->counter);w16(w,t->latch);w16(w,t->state);w8(w,t->output_toggle);w8(w,t->pulse);}static void dec_timer(R*r,cia6526_timer*t){t->counter=r16(r);t->latch=r16(r);t->state=r16(r);t->output_toggle=r8(r);t->pulse=r8(r);}
static void enc_cia(W*w,const cia6526*c){unsigned i;w8(w,c->pra);w8(w,c->prb);w8(w,c->ddra);w8(w,c->ddrb);w8(w,c->sdr);w8(w,c->cra);w8(w,c->crb);enc_timer(w,&c->ta);enc_timer(w,&c->tb);for(i=0;i<4;i++)w8(w,c->tod[i]);for(i=0;i<4;i++)w8(w,c->alarm[i]);for(i=0;i<4;i++)w8(w,c->tod_latch[i]);w8(w,c->tod_latched);w8(w,c->tod_stopped);w8(w,c->tod_pulses);w8(w,c->icr_flags);w8(w,c->icr_mask);w8(w,c->irq_line);w8(w,c->irq_delay);w8(w,c->cnt_level);w8(w,c->sp_level);w8(w,c->flag_level);w8(w,c->serial_shift);w8(w,c->serial_bits);w64(w,c->cycle);}static void dec_cia(R*r,cia6526*c){unsigned i;c->pra=r8(r);c->prb=r8(r);c->ddra=r8(r);c->ddrb=r8(r);c->sdr=r8(r);c->cra=r8(r);c->crb=r8(r);dec_timer(r,&c->ta);dec_timer(r,&c->tb);for(i=0;i<4;i++)c->tod[i]=r8(r);for(i=0;i<4;i++)c->alarm[i]=r8(r);for(i=0;i<4;i++)c->tod_latch[i]=r8(r);c->tod_latched=r8(r);c->tod_stopped=r8(r);c->tod_pulses=r8(r);c->icr_flags=r8(r);c->icr_mask=r8(r);c->irq_line=r8(r);c->irq_delay=r8(r);c->cnt_level=r8(r);c->sp_level=r8(r);c->flag_level=r8(r);c->serial_shift=r8(r);c->serial_bits=r8(r);c->cycle=r64(r);}
static void enc_input(W*w,const c64_input*i){w64(w,i->keyboard);w8(w,i->joystick1);w8(w,i->joystick2);w8(w,(uint8_t)i->restore);}static void dec_input(R*r,c64_input*i){i->keyboard=r64(r);i->joystick1=r8(r);i->joystick2=r8(r);i->restore=r8(r)!=0;}
static void enc_sprite(W*w,const bt_vicii_sprite*s){unsigned i;w16(w,s->x);w8(w,s->y);w8(w,s->dma);w8(w,s->memptr);w8(w,(uint8_t)s->memptr_inc);w8(w,s->exp_flag);for(i=0;i<3;i++)w8(w,s->data[i]);for(i=0;i<3;i++)w8(w,s->next_data[i]);}static void dec_sprite(R*r,bt_vicii_sprite*s){unsigned i;s->x=r16(r);s->y=r8(r);s->dma=r8(r);s->memptr=r8(r);s->memptr_inc=(int8_t)r8(r);s->exp_flag=r8(r);for(i=0;i<3;i++)s->data[i]=r8(r);for(i=0;i<3;i++)s->next_data[i]=r8(r);}
static void enc_vic(W*w,const bt_vicii6569*v){unsigned i;wb(w,v->regs,sizeof(v->regs));w64(w,v->machine_cycle);w64(w,v->frame_number);w64(w,v->line_start_cycle);w16(w,v->raster_line);w16(w,v->raster_irq_line);w8(w,v->raster_cycle);w8(w,v->allow_bad_lines);w8(w,v->badline);w8(w,v->display_state);w8(w,v->rc);w16(w,v->vc);w16(w,v->vcbase);w8(w,v->mem_counter_inc);w8(w,v->memory_fetch_done);w8(w,v->force_display_state);w8(w,v->ycounter_reset_checked);w8(w,v->buf_offset);wb(w,v->matrix,sizeof(v->matrix));wb(w,v->matrix_color,sizeof(v->matrix_color));w8(w,v->irq_flags);w8(w,v->irq_mask);w8(w,v->irq_line);w8(w,v->raster_line0_irq_pending);w8(w,v->sprite_dma_mask);w8(w,v->sprite_fetch_mask);w8(w,v->sprite_display_mask);for(i=0;i<8;i++)enc_sprite(w,&v->sprites[i]);for(i=0;i<BT_VICII_MAX_DMA_SPANS;i++){w64(w,v->sprite_spans[i].first_cycle);w64(w,v->sprite_spans[i].last_cycle);}w8(w,v->sprite_span_count);w8(w,v->ba_low);w8(w,v->cpu_read_stolen);w8(w,v->border_vertical);w8(w,v->border_main);w16(w,v->display_ystart);w16(w,v->display_ystop);w16(w,v->display_xstart);w16(w,v->display_xstop);w16(w,v->next_display_xstart);w16(w,v->next_display_xstop);w8(w,v->display_xstart_pending);w8(w,v->display_xstop_pending);w8(w,v->blank_this_line);w8(w,v->open_left_border);w8(w,v->open_right_border);w8(w,v->xsmooth);wb(w,v->framebuffer,sizeof(v->framebuffer));w64(w,v->completed_frames);}
static void dec_vic(R*r,bt_vicii6569*v){unsigned i;rb(r,v->regs,sizeof(v->regs));v->machine_cycle=r64(r);v->frame_number=r64(r);v->line_start_cycle=r64(r);v->raster_line=r16(r);v->raster_irq_line=r16(r);v->raster_cycle=r8(r);v->allow_bad_lines=r8(r);v->badline=r8(r);v->display_state=r8(r);v->rc=r8(r);v->vc=r16(r);v->vcbase=r16(r);v->mem_counter_inc=r8(r);v->memory_fetch_done=r8(r);v->force_display_state=r8(r);v->ycounter_reset_checked=r8(r);v->buf_offset=r8(r);rb(r,v->matrix,sizeof(v->matrix));rb(r,v->matrix_color,sizeof(v->matrix_color));v->irq_flags=r8(r);v->irq_mask=r8(r);v->irq_line=r8(r);v->raster_line0_irq_pending=r8(r);v->sprite_dma_mask=r8(r);v->sprite_fetch_mask=r8(r);v->sprite_display_mask=r8(r);for(i=0;i<8;i++)dec_sprite(r,&v->sprites[i]);for(i=0;i<BT_VICII_MAX_DMA_SPANS;i++){v->sprite_spans[i].first_cycle=r64(r);v->sprite_spans[i].last_cycle=r64(r);}v->sprite_span_count=r8(r);v->ba_low=r8(r);v->cpu_read_stolen=r8(r);v->border_vertical=r8(r);v->border_main=r8(r);v->display_ystart=r16(r);v->display_ystop=r16(r);v->display_xstart=r16(r);v->display_xstop=r16(r);v->next_display_xstart=r16(r);v->next_display_xstop=r16(r);v->display_xstart_pending=r8(r);v->display_xstop_pending=r8(r);v->blank_this_line=r8(r);v->open_left_border=r8(r);v->open_right_border=r8(r);v->xsmooth=r8(r);rb(r,v->framebuffer,sizeof(v->framebuffer));v->completed_frames=r64(r);}
static void enc_voice(W*w,const bt_sid6581_voice*v){w32(w,v->accumulator);w32(w,v->shift_register);w16(w,v->frequency);w16(w,v->pulse_width);w16(w,v->rate_counter);w8(w,v->control);w8(w,v->attack_decay);w8(w,v->sustain_release);w8(w,v->envelope);w8(w,v->exponential_counter);w8(w,v->exponential_period);w8(w,v->shift_pipeline);w8(w,v->msb_rising);w8(w,v->gate);w32(w,(uint32_t)v->env_state);}static void dec_voice(R*r,bt_sid6581_voice*v){v->accumulator=r32(r);v->shift_register=r32(r);v->frequency=r16(r);v->pulse_width=r16(r);v->rate_counter=r16(r);v->control=r8(r);v->attack_decay=r8(r);v->sustain_release=r8(r);v->envelope=r8(r);v->exponential_counter=r8(r);v->exponential_period=r8(r);v->shift_pipeline=r8(r);v->msb_rising=r8(r);v->gate=r8(r);v->env_state=(bt_sid6581_env_state)r32(r);}
static void enc_sid(W*w,const bt_sid6581*s){unsigned i;wb(w,s->regs,sizeof(s->regs));for(i=0;i<3;i++)enc_voice(w,&s->voice[i]);w64(w,s->cycle);w64(w,s->emitted_samples);w32(w,s->clock_hz);w32(w,s->sample_rate);w32(w,s->sample_accumulator);w32(w,(uint32_t)s->filter_low);w32(w,(uint32_t)s->filter_band);w32(w,(uint32_t)s->filter_high);w32(w,(uint32_t)s->last_mixed);w16(w,(uint16_t)s->last_sample);w8(w,s->bus_latch);w16(w,s->bus_latch_ttl);w8(w,s->failed);}static void dec_sid(R*r,bt_sid6581*s){unsigned i;rb(r,s->regs,sizeof(s->regs));for(i=0;i<3;i++)dec_voice(r,&s->voice[i]);s->cycle=r64(r);s->emitted_samples=r64(r);s->clock_hz=r32(r);s->sample_rate=r32(r);s->sample_accumulator=r32(r);s->filter_low=(int32_t)r32(r);s->filter_band=(int32_t)r32(r);s->filter_high=(int32_t)r32(r);s->last_mixed=(int32_t)r32(r);s->last_sample=(int16_t)r16(r);s->bus_latch=r8(r);s->bus_latch_ttl=r16(r);s->failed=r8(r);}
static void enc_iec(W*w,const bt_iec_bus*b){w8(w,b->c64_atn_low);w8(w,b->c64_clk_low);w8(w,b->c64_data_low);w8(w,b->drive_clk_low);w8(w,b->drive_data_out);w8(w,b->drive_data_low);w8(w,b->drive_atna);w8(w,b->atn);w8(w,b->clk);w8(w,b->data);}static void dec_iec(R*r,bt_iec_bus*b){b->c64_atn_low=r8(r);b->c64_clk_low=r8(r);b->c64_data_low=r8(r);b->drive_clk_low=r8(r);b->drive_data_out=r8(r);b->drive_data_low=r8(r);b->drive_atna=r8(r);b->atn=r8(r);b->clk=r8(r);b->data=r8(r);}
static void enc_via(W*w,const bt_via6522*v){w8(w,v->orb);w8(w,v->ora);w8(w,v->ddrb);w8(w,v->ddra);w8(w,v->sr);w8(w,v->acr);w8(w,v->pcr);w8(w,v->ifr);w8(w,v->ier);w16(w,v->t1c);w16(w,v->t1l);w16(w,v->t2c);w8(w,v->t1_running);w8(w,v->t2_running);w8(w,v->t1_fired);w8(w,v->t2_fired);w8(w,v->pb7);w8(w,v->ca1);w8(w,v->cb1);w8(w,v->ca2);w8(w,v->cb2);w8(w,v->unsupported);w64(w,v->cycle);}static void dec_via(R*r,bt_via6522*v){v->orb=r8(r);v->ora=r8(r);v->ddrb=r8(r);v->ddra=r8(r);v->sr=r8(r);v->acr=r8(r);v->pcr=r8(r);v->ifr=r8(r);v->ier=r8(r);v->t1c=r16(r);v->t1l=r16(r);v->t2c=r16(r);v->t1_running=r8(r);v->t2_running=r8(r);v->t1_fired=r8(r);v->t2_fired=r8(r);v->pb7=r8(r);v->ca1=r8(r);v->cb1=r8(r);v->ca2=r8(r);v->cb2=r8(r);v->unsupported=r8(r);v->cycle=r64(r);}
static void enc_d64(W*w,const bt_d64_image*d){uint16_t i;w8(w,d->side);w8(w,d->attached);w8(w,d->write_protected);w16(w,d->overlay_count);for(i=0;i<d->overlay_count&&i<BT_D64_SECTORS;i++){const bt_d64_overlay_entry*e=&d->overlay[i];w16(w,e->sector_index);w8(w,e->used);wb(w,e->bytes,sizeof(e->bytes));}}
static void dec_d64(R*r,bt_d64_image*d){uint16_t i,n;d->side=r8(r);d->attached=r8(r);d->write_protected=r8(r);n=r16(r);if(n>BT_D64_SECTORS){r->ok=0;return;}memset(d->overlay,0,sizeof(d->overlay));d->overlay_count=n;for(i=0;i<n;i++){bt_d64_overlay_entry*e=&d->overlay[i];e->sector_index=r16(r);e->used=r8(r);rb(r,e->bytes,sizeof(e->bytes));if(!e->used||e->sector_index>=BT_D64_SECTORS)r->ok=0;}}
static void enc_shadow_stack(W*w,const bt_c06_shadow_frame*a,size_t n){uint32_t i;w32(w,(uint32_t)n);for(i=0;i<n&&i<BT_C06_SHADOW_CAPACITY;i++){const bt_c06_shadow_frame*f=&a[i];w16(w,f->return_pc);w16(w,f->identity_key);w32(w,f->generation);w8(w,f->processor_domain);w8(w,f->c64_view);w8(w,f->kind);}}
static void dec_shadow_stack(R*r,bt_c06_shadow_frame*a,size_t*n,uint8_t expected_proc){uint32_t i,q=r32(r);if(q>BT_C06_SHADOW_CAPACITY){r->ok=0;return;}memset(a,0,sizeof(bt_c06_shadow_frame)*BT_C06_SHADOW_CAPACITY);*n=q;for(i=0;i<q;i++){bt_c06_shadow_frame*f=&a[i];f->return_pc=r16(r);f->identity_key=r16(r);f->generation=r32(r);f->processor_domain=r8(r);f->c64_view=r8(r);f->kind=r8(r);if(f->identity_key>BT_C06_REGISTRY_IDENTITY_COUNT||f->processor_domain!=expected_proc)r->ok=0;}}
static void enc_registry(W*w,const bt_c06_registry*g){uint32_t i;w8(w,g->c64_view);w8(w,g->failed);for(i=0;i<65536u;i++)w16(w,g->c64_owner[i]);for(i=0;i<65536u;i++)w16(w,g->drive_owner[i]);for(i=0;i<=BT_C06_REGISTRY_IDENTITY_COUNT;i++)w32(w,g->generation[i]);wb(w,g->blocked,BT_C06_REGISTRY_BLOCK_COUNT);enc_shadow_stack(w,g->c64_shadow,g->c64_shadow_depth);enc_shadow_stack(w,g->drive_shadow,g->drive_shadow_depth);}
static void dec_registry(R*r,bt_c06_registry*g){uint32_t i;g->c64_view=r8(r);g->failed=r8(r);for(i=0;i<65536u;i++)g->c64_owner[i]=r16(r);for(i=0;i<65536u;i++)g->drive_owner[i]=r16(r);for(i=0;i<=BT_C06_REGISTRY_IDENTITY_COUNT;i++)g->generation[i]=r32(r);rb(r,g->blocked,BT_C06_REGISTRY_BLOCK_COUNT);dec_shadow_stack(r,g->c64_shadow,&g->c64_shadow_depth,BT_C06_PROCESSOR_C64_6510);dec_shadow_stack(r,g->drive_shadow,&g->drive_shadow_depth,BT_C06_PROCESSOR_DRIVE_6502);}
static void enc_kernal(W*w,const bt_kernal_target_state*k){uint32_t i;w8(w,k->lfn);w8(w,k->device);w8(w,k->secondary);w8(w,k->name_len);wb(w,k->name,sizeof(k->name));w8(w,k->current_input);w8(w,k->current_output);w8(w,k->status_90);w8(w,k->bootstrapped);w32(w,k->service_count);w8(w,k->aot_call_depth);for(i=0;i<32u;i++)w16(w,k->aot_call_return[i]);}
static void dec_kernal(R*r,bt_kernal_target_state*k){uint32_t i;k->lfn=r8(r);k->device=r8(r);k->secondary=r8(r);k->name_len=r8(r);rb(r,k->name,sizeof(k->name));k->current_input=r8(r);k->current_output=r8(r);k->status_90=r8(r);k->bootstrapped=r8(r);k->service_count=r32(r);k->aot_call_depth=r8(r);for(i=0;i<32u;i++)k->aot_call_return[i]=r16(r);if(k->name_len>16u||k->aot_call_depth>32u)r->ok=0;}
static void enc_machine(W*w,const bt_c64_machine*m){enc_sched(w,&m->scheduler);enc_bus(w,&m->bus);enc_cpu(w,&m->cpu);enc_cia(w,&m->cia1);enc_cia(w,&m->cia2);enc_input(w,&m->input);enc_vic(w,&m->vicii);enc_sid(w,&m->sid);w8(w,m->cia2_pa_input);w8(w,m->cia2_pb_input);w8(w,m->userport_pb_output);w8(w,m->userport_pb_ddr);w8(w,m->external_irq);w8(w,m->external_nmi);w8(w,m->restore_line);w32(w,m->cpu_hz);w32(w,m->power_hz);w32(w,m->tod_accumulator);w64(w,m->last_rendezvous_cycle);w64(w,m->cpu_stall_cycles);w64(w,m->last_cpu_physical_cycle);w64(w,m->vic_read_stall_cycles);w16(w,m->cpu_rmw_addr);w8(w,m->cpu_rmw_pending);w8(w,m->cpu_write_phase);w8(w,m->failed);}static void dec_machine(R*r,bt_c64_machine*m){dec_sched(r,&m->scheduler);dec_bus(r,&m->bus);dec_cpu(r,&m->cpu);dec_cia(r,&m->cia1);dec_cia(r,&m->cia2);dec_input(r,&m->input);dec_vic(r,&m->vicii);dec_sid(r,&m->sid);m->cia2_pa_input=r8(r);m->cia2_pb_input=r8(r);m->userport_pb_output=r8(r);m->userport_pb_ddr=r8(r);m->external_irq=r8(r);m->external_nmi=r8(r);m->restore_line=r8(r);m->cpu_hz=r32(r);m->power_hz=r32(r);m->tod_accumulator=r32(r);m->last_rendezvous_cycle=r64(r);m->cpu_stall_cycles=r64(r);m->last_cpu_physical_cycle=r64(r);m->vic_read_stall_cycles=r64(r);m->cpu_rmw_addr=r16(r);m->cpu_rmw_pending=r8(r);m->cpu_write_phase=r8(r);m->failed=r8(r);}
static void enc_drive(W*w,const bt_1541_target*d){enc_cpu(w,&d->cpu);enc_via(w,&d->via_iec);enc_via(w,&d->via_disk);wb(w,d->ram,sizeof(d->ram));enc_d64(w,&d->sides[0]);enc_d64(w,&d->sides[1]);w8(w,d->active_side);w8(w,d->inserted);w8(w,d->motor_on);w8(w,d->activity_led);w8(w,d->density_zone);w8(w,d->stepper_phase);w8(w,d->half_track);w8(w,d->disk_byte);w8(w,d->disk_write_byte);w8(w,d->disk_output_enable);w8(w,d->disk_set_overflow_enable);w8(w,d->sync_level);w8(w,d->sync_ff_run);w8(w,d->byte_ready_level);w8(w,d->write_protect_level);w8(w,(uint8_t)((d->failed&1u)|((d->semantic_fastloader_mode&1u)<<1)));w32(w,d->executing_identity_key);w16(w,d->executing_pc);w64(w,d->c64_cycle_seen);w64(w,d->drive_cycle_target);w64(w,d->media_cycle_accumulator);w64(w,d->media_byte_index);w32(w,(uint32_t)d->gcr_track_bytes);wb(w,d->gcr_track,d->gcr_track_bytes);w32(w,(uint32_t)d->status);}static void dec_drive(R*r,bt_1541_target*d){uint32_t n;dec_cpu(r,&d->cpu);dec_via(r,&d->via_iec);dec_via(r,&d->via_disk);rb(r,d->ram,sizeof(d->ram));dec_d64(r,&d->sides[0]);dec_d64(r,&d->sides[1]);d->active_side=r8(r);d->inserted=r8(r);d->motor_on=r8(r);d->activity_led=r8(r);d->density_zone=r8(r);d->stepper_phase=r8(r);d->half_track=r8(r);d->disk_byte=r8(r);d->disk_write_byte=r8(r);d->disk_output_enable=r8(r);d->disk_set_overflow_enable=r8(r);d->sync_level=r8(r);d->sync_ff_run=r8(r);d->byte_ready_level=r8(r);d->write_protect_level=r8(r);{uint8_t drive_flags=r8(r);d->failed=(uint8_t)(drive_flags&1u);d->semantic_fastloader_mode=(uint8_t)((drive_flags>>1)&1u);}d->executing_identity_key=r32(r);d->executing_pc=r16(r);d->c64_cycle_seen=r64(r);d->drive_cycle_target=r64(r);d->media_cycle_accumulator=r64(r);d->media_byte_index=r64(r);n=r32(r);if(n>BT_GCR_MAX_TRACK_BYTES){r->ok=0;return;}d->gcr_track_bytes=n;memset(d->gcr_track,0,sizeof(d->gcr_track));rb(r,d->gcr_track,n);d->status=(bt_1541_target_status)r32(r);}
static void enc_payload(W*w,const bt_static_core*c){w64(w,c->deterministic_seed);w32(w,(uint32_t)c->last_stop);w32(w,(uint32_t)c->diag.view.code);w32(w,(uint32_t)c->diag.view.stop_reason);w32(w,c->executing_identity_key);w16(w,c->executing_pc);enc_registry(w,&c->registry);enc_kernal(w,&c->kernal_target);enc_iec(w,&c->iec);enc_machine(w,&c->machine);enc_drive(w,&c->drive);}
static void dec_payload(R*r,bt_static_core*c){c->deterministic_seed=r64(r);c->last_stop=(bt_static_stop_reason)r32(r);c->diag.view.code=(bt_static_error)r32(r);c->diag.view.stop_reason=(bt_static_stop_reason)r32(r);c->executing_identity_key=r32(r);c->executing_pc=r16(r);dec_registry(r,&c->registry);dec_kernal(r,&c->kernal_target);dec_iec(r,&c->iec);dec_machine(r,&c->machine);dec_drive(r,&c->drive);snprintf(c->diag.message,sizeof(c->diag.message),"%s",bt_static_error_name(c->diag.view.code));c->diag.view.message=c->diag.message;c->diag.view.cycle=c->machine.scheduler.cycle;c->diag.view.c64_pc=c->machine.cpu.pc;c->diag.view.drive_pc=c->drive.cpu.pc;}
static int semantic_ok(const bt_static_core*c){uint32_t i;if(!c||c->registry.c64_view>7u||c->registry.c64_shadow_depth>BT_C06_SHADOW_CAPACITY||c->registry.drive_shadow_depth>BT_C06_SHADOW_CAPACITY||c->kernal_target.name_len>16u||c->kernal_target.aot_call_depth>32u)return 0;for(i=0;i<65536u;i++)if(c->registry.c64_owner[i]>BT_C06_REGISTRY_IDENTITY_COUNT||c->registry.drive_owner[i]>BT_C06_REGISTRY_IDENTITY_COUNT)return 0;if(c->machine.cpu_hz!=BT_C64_PAL_CPU_HZ||c->machine.power_hz!=BT_C64_PAL_POWER_HZ||c->machine.sid.sample_rate!=BT_STATIC_CORE_AUDIO_SAMPLE_RATE)return 0;if(c->machine.scheduler.ticker_count!=1u)return 0;if(c->drive.active_side<1u||c->drive.active_side>2u||c->drive.half_track<2u||c->drive.half_track>70u||c->drive.gcr_track_bytes>BT_GCR_MAX_TRACK_BYTES||c->drive.failed>1u||c->drive.semantic_fastloader_mode>1u)return 0;if(c->drive.sides[0].side!=1u||c->drive.sides[1].side!=2u||!c->drive.sides[0].attached||!c->drive.sides[1].attached)return 0;if(c->drive.gcr_track_bytes&&c->drive.media_byte_index>=c->drive.gcr_track_bytes)return 0;return 1;}
static size_t payload_size(const bt_static_core*c){W w={0};w.ok=1;enc_payload(&w,c);return w.ok?w.pos:0u;}
size_t bt_static_snapshot_size_internal(const bt_static_core*c){size_t p;if(!c||!c->reset_done)return 0u;p=payload_size(c);return p?SNAP_HEADER_BYTES+p:0u;}
static void write_header(uint8_t*h,const bt_static_core*c,size_t payload,const uint8_t psha[32]){W w={h,SNAP_HEADER_BYTES,0,1};uint8_t x[32];unsigned i;wb(&w,SNAP_MAGIC,8);w32(&w,BT_STATIC_CORE_SNAPSHOT_VERSION);w32(&w,BT_STATIC_CORE_API_VERSION);w32(&w,SNAP_ENDIAN_MARKER);w32(&w,SNAP_HEADER_BYTES);w64(&w,payload);hex32(bt_static_core_aot_authority_sha256(),x);wb(&w,x,32);hex32(PROFILE_SHA,x);wb(&w,x,32);for(i=0;i<4;i++)wb(&w,c->rom_hash[i],32);for(i=0;i<2;i++)wb(&w,c->media_hash[i],32);wb(&w,psha,32);}
static int check_header(const bt_static_core*c,const uint8_t*h,size_t n,size_t*payload,const uint8_t**want_sha){R r={h,n,0,1};uint8_t magic[8]={0},x[32]={0},got[32]={0};uint32_t ver,api,endian,hb;uint64_t pb;unsigned i;if(n<SNAP_HEADER_BYTES)return BT_STATIC_ERR_SNAPSHOT_TRUNCATED;rb(&r,magic,8);if(memcmp(magic,SNAP_MAGIC,8)!=0)return BT_STATIC_ERR_SNAPSHOT_MAGIC;ver=r32(&r);api=r32(&r);endian=r32(&r);hb=r32(&r);pb=r64(&r);if(ver!=BT_STATIC_CORE_SNAPSHOT_VERSION||api!=BT_STATIC_CORE_API_VERSION)return BT_STATIC_ERR_SNAPSHOT_VERSION;if(endian!=SNAP_ENDIAN_MARKER||hb!=SNAP_HEADER_BYTES||pb>SIZE_MAX||SNAP_HEADER_BYTES+(size_t)pb!=n)return BT_STATIC_ERR_SNAPSHOT_TRUNCATED;rb(&r,got,32);if(!r.ok||!hex32(bt_static_core_aot_authority_sha256(),x))return BT_STATIC_ERR_SNAPSHOT_IDENTITY;if(memcmp(got,x,32)!=0)return BT_STATIC_ERR_SNAPSHOT_IDENTITY;rb(&r,got,32);if(!r.ok||!hex32(PROFILE_SHA,x))return BT_STATIC_ERR_SNAPSHOT_IDENTITY;if(memcmp(got,x,32)!=0)return BT_STATIC_ERR_SNAPSHOT_IDENTITY;for(i=0;i<4;i++){rb(&r,got,32);if(!r.ok||memcmp(got,c->rom_hash[i],32)!=0)return BT_STATIC_ERR_SNAPSHOT_IDENTITY;}for(i=0;i<2;i++){rb(&r,got,32);if(!r.ok||memcmp(got,c->media_hash[i],32)!=0)return BT_STATIC_ERR_SNAPSHOT_IDENTITY;}*want_sha=h+r.pos;*payload=(size_t)pb;return BT_STATIC_OK;}
int bt_static_snapshot_save_internal(const bt_static_core*c,void*dst,size_t n){size_t ps,total;uint8_t*o=(uint8_t*)dst,ph[32];W w;if(!c||!dst||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;ps=payload_size(c);total=SNAP_HEADER_BYTES+ps;if(!ps||n<total)return BT_STATIC_ERR_BAD_ARGUMENT;w.p=o+SNAP_HEADER_BYTES;w.cap=ps;w.pos=0;w.ok=1;enc_payload(&w,c);if(!w.ok||w.pos!=ps)return BT_STATIC_ERR_INTERNAL;bt_sha256(o+SNAP_HEADER_BYTES,ps,ph);write_header(o,c,ps,ph);bt_static_emit_trace(c,BT_STATIC_TRACE_SNAPSHOT,0u,c->machine.cpu.pc,1u,ps);return BT_STATIC_OK;}
static int prepare_temp_like(const bt_static_core*c,bt_static_core*t){memset(t,0,sizeof(*t));t->allocator=c->allocator;t->trace=c->trace;memcpy(t->basic,c->basic,sizeof(t->basic));memcpy(t->kernal,c->kernal,sizeof(t->kernal));memcpy(t->chargen,c->chargen,sizeof(t->chargen));memcpy(t->drive_rom,c->drive_rom,sizeof(t->drive_rom));memcpy(t->media_bytes,c->media_bytes,sizeof(t->media_bytes));memcpy(t->rom_hash,c->rom_hash,sizeof(t->rom_hash));memcpy(t->media_hash,c->media_hash,sizeof(t->media_hash));t->system_loaded=c->system_loaded;t->media_loaded=c->media_loaded;t->diag.view.message=t->diag.message;if(!bt_static_prepare_runtime(t))return 0;t->reset_done=1u;return 1;}
static int decode_checked(bt_static_core*c,const uint8_t*p,size_t n){R r={p,n,0,1};dec_payload(&r,c);if(!r.ok||r.pos!=n)return 0;if(!semantic_ok(c))return 0;bt_static_core_audio_clear(c);return 1;}
int bt_static_snapshot_load_internal(bt_static_core*c,const void*src,size_t n){const uint8_t*h=(const uint8_t*)src,*want;uint8_t got[32];size_t ps;int e;bt_static_core*tmp;if(!c||!src||!c->reset_done)return BT_STATIC_ERR_BAD_ARGUMENT;e=check_header(c,h,n,&ps,&want);if(e!=BT_STATIC_OK){bt_static_set_diag(c,(bt_static_error)e,BT_STATIC_STOP_FATAL,bt_static_error_name((bt_static_error)e));return e;}bt_sha256(h+SNAP_HEADER_BYTES,ps,got);if(memcmp(got,want,32)!=0){bt_static_set_diag(c,BT_STATIC_ERR_SNAPSHOT_CORRUPT,BT_STATIC_STOP_FATAL,"snapshot payload SHA-256 mismatch");return BT_STATIC_ERR_SNAPSHOT_CORRUPT;}tmp=(bt_static_core*)bt_static_alloc(c,sizeof(*tmp));if(!tmp){bt_static_set_diag(c,BT_STATIC_ERR_INTERNAL,BT_STATIC_STOP_FATAL,"snapshot preflight allocation failed");return BT_STATIC_ERR_INTERNAL;}if(!prepare_temp_like(c,tmp)||!decode_checked(tmp,h+SNAP_HEADER_BYTES,ps)){bt_static_free(c,tmp);bt_static_set_diag(c,BT_STATIC_ERR_SNAPSHOT_STATE,BT_STATIC_STOP_FATAL,"snapshot state contract rejected");return BT_STATIC_ERR_SNAPSHOT_STATE;}bt_static_free(c,tmp);if(!bt_static_prepare_runtime(c)||!decode_checked(c,h+SNAP_HEADER_BYTES,ps)){bt_static_set_diag(c,BT_STATIC_ERR_INTERNAL,BT_STATIC_STOP_FATAL,"validated snapshot could not be installed");return BT_STATIC_ERR_INTERNAL;}c->reset_done=1u;bt_static_emit_trace(c,BT_STATIC_TRACE_SNAPSHOT,0u,c->machine.cpu.pc,2u,ps);return BT_STATIC_OK;}
int bt_static_snapshot_state_hash_internal(const bt_static_core*c,uint8_t out[32]){size_t n;uint8_t*p;int e;if(!c||!out)return BT_STATIC_ERR_BAD_ARGUMENT;n=bt_static_snapshot_size_internal(c);if(!n)return BT_STATIC_ERR_BAD_ARGUMENT;p=(uint8_t*)bt_static_alloc(c,n);if(!p)return BT_STATIC_ERR_INTERNAL;e=bt_static_snapshot_save_internal(c,p,n);if(e==BT_STATIC_OK)bt_sha256(p,n,out);bt_static_free(c,p);return e;}
