#include "bt_d64.h"
#include "bt_sha256.h"
#include <string.h>
static const char *H1="135ac55a444ed8dcf5648b61cf3e1953e4dc342b135bbfcc6c550dd55a3af862";
static const char *H2="1806a717ee66e6b67652ba7210e82fa150a000986c3ec9234e71fa2fc9ef4769";
static void st(bt_media_status*s,bt_media_status v){if(s)*s=v;}
const char *bt_d64_expected_sha256(unsigned side){return side==1u?H1:(side==2u?H2:0);}
unsigned bt_d64_sectors_on_track(unsigned t){if(t<1u||t>35u)return 0u;if(t<=17u)return 21u;if(t<=24u)return 19u;if(t<=30u)return 18u;return 17u;}
bool bt_d64_ts_to_index(unsigned t,unsigned s,uint16_t *idx){unsigned i=0,x;if(!idx||!bt_d64_sectors_on_track(t)||s>=bt_d64_sectors_on_track(t))return false;for(x=1;x<t;x++)i+=bt_d64_sectors_on_track(x);*idx=(uint16_t)(i+s);return i+s<BT_D64_SECTORS;}
static bt_d64_overlay_entry *ov_find(bt_d64_image*d,uint16_t idx){unsigned i;for(i=0;i<d->overlay_count;i++)if(d->overlay[i].used&&d->overlay[i].sector_index==idx)return &d->overlay[i];return 0;}
static const bt_d64_overlay_entry *ov_find_c(const bt_d64_image*d,uint16_t idx){unsigned i;for(i=0;i<d->overlay_count;i++)if(d->overlay[i].used&&d->overlay[i].sector_index==idx)return &d->overlay[i];return 0;}
bool bt_d64_attach(bt_d64_image*d,unsigned side,const uint8_t*b,size_t n,bool wp,bt_media_status*s){uint8_t h[32];const char*e=bt_d64_expected_sha256(side);if(!d||!b||!e){st(s,BT_MEDIA_BAD_HASH);return false;}if(n!=BT_D64_SIZE){st(s,BT_MEDIA_BAD_SIZE);return false;}bt_sha256(b,n,h);if(!bt_sha256_equal_hex(h,e)){st(s,BT_MEDIA_BAD_HASH);return false;}memset(d,0,sizeof(*d));d->base=b;d->size=n;d->side=(uint8_t)side;d->attached=1u;d->write_protected=(uint8_t)wp;st(s,BT_MEDIA_OK);return true;}
bool bt_d64_read_sector(const bt_d64_image*d,unsigned t,unsigned s,uint8_t out[256],bt_media_status*status){uint16_t i;const bt_d64_overlay_entry*o;if(!d||!d->attached||!d->base){st(status,BT_MEDIA_NO_MEDIA);return false;}if(!out||!bt_d64_ts_to_index(t,s,&i)){st(status,BT_MEDIA_BAD_TRACK_SECTOR);return false;}o=ov_find_c(d,i);memcpy(out,o?o->bytes:d->base+(size_t)i*256u,256u);st(status,BT_MEDIA_OK);return true;}
bool bt_d64_write_sector(bt_d64_image*d,unsigned t,unsigned s,const uint8_t in[256],bt_media_status*status){uint16_t i;bt_d64_overlay_entry*o;if(!d||!d->attached||!d->base){st(status,BT_MEDIA_NO_MEDIA);return false;}if(d->write_protected){st(status,BT_MEDIA_WRITE_PROTECTED);return false;}if(!in||!bt_d64_ts_to_index(t,s,&i)){st(status,BT_MEDIA_BAD_TRACK_SECTOR);return false;}o=ov_find(d,i);if(!o){if(d->overlay_count>=BT_D64_SECTORS){st(status,BT_MEDIA_OVERLAY_FULL);return false;}o=&d->overlay[d->overlay_count++];memset(o,0,sizeof(*o));o->sector_index=i;o->used=1u;}memcpy(o->bytes,in,256u);st(status,BT_MEDIA_OK);return true;}
static void petscii_name(char out[17],const uint8_t in[16]){unsigned i,n=16u;while(n&&in[n-1u]==0xa0u)n--;for(i=0;i<n;i++){uint8_t c=in[i];out[i]=(char)((c>=0x20u&&c<=0x7eu)?c:'?');}out[n]='\0';}
static int name_eq(const char*a,const char*b){unsigned i=0;while(a[i]&&b[i]){char x=a[i],y=b[i];if(x>='a'&&x<='z')x=(char)(x-32);if(y>='a'&&y<='z')y=(char)(y-32);if(x!=y)return 0;i++;}return a[i]==b[i];}
bool bt_d64_find_file(const bt_d64_image*d,const char*name,bt_d64_file*out,bt_media_status*status){uint8_t t=18u,s=1u,sec[256];unsigned guard=0;if(!d||!name||!out){st(status,BT_MEDIA_DIRECTORY_ERROR);return false;}while(t){unsigned slot;if(++guard>18u){st(status,BT_MEDIA_DIRECTORY_ERROR);return false;}if(!bt_d64_read_sector(d,t,s,sec,status))return false;for(slot=0;slot<8u;slot++){const uint8_t*e=sec+2u+32u*slot;char n[17];if((e[0]&7u)==0u)continue;petscii_name(n,e+3);if(name_eq(n,name)){memset(out,0,sizeof(*out));memcpy(out->name,n,17);out->type=e[0];out->start_track=e[1];out->start_sector=e[2];out->blocks=(uint16_t)(e[28]|((uint16_t)e[29]<<8));st(status,BT_MEDIA_OK);return true;}}t=sec[0];s=sec[1];}st(status,BT_MEDIA_FILE_NOT_FOUND);return false;}
bool bt_d64_read_file(const bt_d64_image*d,const bt_d64_file*f,uint8_t*out,size_t cap,size_t*used,bt_media_status*status){uint8_t t,s,sec[256];size_t n=0;unsigned guard=0;if(!d||!f||!out){st(status,BT_MEDIA_DIRECTORY_ERROR);return false;}t=f->start_track;s=f->start_sector;while(t){uint8_t nt,ns;size_t take;if(++guard>BT_D64_SECTORS){st(status,BT_MEDIA_DIRECTORY_ERROR);return false;}if(!bt_d64_read_sector(d,t,s,sec,status))return false;nt=sec[0];ns=sec[1];take=nt?254u:(ns?((size_t)ns-1u):0u);if(n+take>cap){st(status,BT_MEDIA_OVERLAY_FULL);return false;}memcpy(out+n,sec+2,take);n+=take;t=nt;s=ns;}if(used)*used=n;st(status,BT_MEDIA_OK);return true;}
void bt_d64_clear_overlay(bt_d64_image*d){if(d){d->overlay_count=0u;memset(d->overlay,0,sizeof(d->overlay));}}
