#include "cia6526.h"
#include <string.h>
enum {T_START=0x001,T_COUNT2=0x002,T_STEP=0x004,T_ONESHOT_CR=0x008,T_FLOAD=0x010,T_PHI2=0x020,T_COUNT3=0x040,T_LOAD1=0x080,T_ONESHOT0=0x100,T_LOAD=0x200,T_OUT=0x400,T_COUNT=0x800,T_ONESHOT=0x1000,T_CR_MASK=0x039};
static uint16_t timer_next(uint16_t s){uint16_t n=(uint16_t)(s&(T_START|T_ONESHOT_CR|T_PHI2));if((s&T_START)&&(s&T_PHI2))n|=T_COUNT2;if((s&T_COUNT2)||((s&T_STEP)&&(s&T_START)))n|=T_COUNT3;if(s&T_COUNT3)n|=T_COUNT;if(s&T_FLOAD)n|=T_LOAD1;if(s&T_LOAD1)n|=T_LOAD;if(s&T_ONESHOT_CR)n|=T_ONESHOT0;if(s&T_ONESHOT0)n|=T_ONESHOT;return n;}
static bool timer_cycle(cia6526_timer *t){uint16_t s=t->state;bool under=false;if(t->pulse)t->pulse--;if(t->counter&&(s&T_COUNT3))t->counter--;s=timer_next(s);if(t->counter==0u&&(s&T_COUNT3)){s|=(T_LOAD|T_OUT);under=true;}if(s&T_LOAD){t->counter=t->latch;s&=(uint16_t)~T_COUNT3;}if((s&T_OUT)&&(s&(T_ONESHOT|T_ONESHOT0)))s&=(uint16_t)~(T_START|T_COUNT2);t->state=s;return under;}
static void timer_ctrl(cia6526_timer *t,uint8_t value,bool phi2){t->state&=(uint16_t)~T_CR_MASK;t->state|=(uint16_t)(value&T_CR_MASK);if(phi2)t->state|=T_PHI2;else t->state&=(uint16_t)~T_PHI2;}
static void set_source(cia6526 *c,uint8_t bit){c->icr_flags|=bit;if((c->icr_mask&bit)&&!c->irq_line&&c->irq_delay==0u)c->irq_delay=1u;}
static void update_irq(cia6526 *c){if(c->irq_delay){c->irq_delay--;if(c->irq_delay==0u&&(c->icr_flags&c->icr_mask))c->irq_line=1u;}if(!(c->icr_flags&c->icr_mask))c->irq_line=0u;}
static uint8_t bcd_inc(uint8_t x,uint8_t limit){uint8_t lo=(uint8_t)(x&0x0fu),hi=(uint8_t)((x>>4)&0x0fu);lo++;if(lo>=10u){lo=0;hi++;}x=(uint8_t)((hi<<4)|lo);return x>limit?0u:x;}
static void tod_advance(cia6526 *c){uint8_t h,pm;if(c->tod_stopped)return;c->tod[0]++;if(c->tod[0]<10u)goto done;c->tod[0]=0;c->tod[1]=bcd_inc(c->tod[1],0x59);if(c->tod[1]!=0u)goto done;c->tod[2]=bcd_inc(c->tod[2],0x59);if(c->tod[2]!=0u)goto done;h=(uint8_t)(c->tod[3]&0x1fu);pm=(uint8_t)(c->tod[3]&0x80u);if(h==0x11u){h=0x12u;pm^=0x80u;}else if(h==0x12u)h=0x01u;else h=bcd_inc(h,0x12);c->tod[3]=(uint8_t)(h|pm);done:if(memcmp(c->tod,c->alarm,4)==0)set_source(c,CIA6526_ICR_TOD);}
static uint8_t driven(uint8_t latch,uint8_t ddr){return (uint8_t)((latch&ddr)|((uint8_t)~ddr));}
static void notify(cia6526 *c,unsigned port){if(c->port_changed){uint8_t l=port?c->prb:c->pra,d=port?c->ddrb:c->ddra;c->port_changed(c->io_ctx,port,l,d,driven(l,d));}}
void cia6526_reset(cia6526 *c){void *ctx=c->io_ctx;cia6526_pin_read_fn pr=c->pin_read;cia6526_port_changed_fn pc=c->port_changed;memset(c,0,sizeof(*c));c->io_ctx=ctx;c->pin_read=pr;c->port_changed=pc;c->ta.counter=c->ta.latch=0xffffu;c->tb.counter=c->tb.latch=0xffffu;c->tod[3]=1u;c->tod_latch[3]=1u;c->cnt_level=1u;c->sp_level=1u;c->flag_level=1u;notify(c,0);notify(c,1);}
void cia6526_init(cia6526 *c,void *ctx,cia6526_pin_read_fn pr,cia6526_port_changed_fn pc){memset(c,0,sizeof(*c));c->io_ctx=ctx;c->pin_read=pr;c->port_changed=pc;cia6526_reset(c);}
static void timer_underflow_output(cia6526 *c,cia6526_timer *t,uint8_t cr,uint8_t source){set_source(c,source);if(cr&0x02u){if(cr&0x04u)t->output_toggle^=1u;else t->pulse=1u;}if(source==CIA6526_ICR_TA&&(c->cra&0x40u)){if(c->serial_bits==0u){c->serial_shift=c->sdr;c->serial_bits=8u;}if(c->serial_bits){c->sp_level=(uint8_t)((c->serial_shift&0x80u)!=0u);c->serial_shift<<=1;c->serial_bits--;if(c->serial_bits==0u)set_source(c,CIA6526_ICR_SDR);}}}
void cia6526_tick(cia6526 *c,uint64_t cycle){bool ua,ub=false;uint8_t tbmode;if(!c)return;c->cycle=cycle;update_irq(c);ua=timer_cycle(&c->ta);if(ua)timer_underflow_output(c,&c->ta,c->cra,CIA6526_ICR_TA);tbmode=(uint8_t)((c->crb>>5)&3u);if(tbmode==0u)ub=timer_cycle(&c->tb);else{ub=timer_cycle(&c->tb);if(ua&&(tbmode==2u||(tbmode==3u&&c->cnt_level)))c->tb.state|=T_STEP;}if(ub)timer_underflow_output(c,&c->tb,c->crb,CIA6526_ICR_TB);}
static uint8_t port_read(const cia6526 *c,unsigned port){uint8_t latch=port?c->prb:c->pra,ddr=port?c->ddrb:c->ddra,pins=c->pin_read?c->pin_read(c->io_ctx,port,c->pra,c->ddra,c->prb,c->ddrb):0xffu;uint8_t v=(uint8_t)(driven(latch,ddr)&pins);if(port){if(c->cra&0x02u){v&=0xbfu;if((c->cra&0x04u)?c->ta.output_toggle:(c->ta.pulse!=0u))v|=0x40u;}if(c->crb&0x02u){v&=0x7fu;if((c->crb&0x04u)?c->tb.output_toggle:(c->tb.pulse!=0u))v|=0x80u;}}return v;}
uint8_t cia6526_peek(const cia6526 *c,uint8_t r){r&=0x0fu;switch(r){case 0:return port_read(c,0);case 1:return port_read(c,1);case 2:return c->ddra;case 3:return c->ddrb;case 4:return (uint8_t)c->ta.counter;case 5:return (uint8_t)(c->ta.counter>>8);case 6:return (uint8_t)c->tb.counter;case 7:return (uint8_t)(c->tb.counter>>8);case 8:case 9:case 10:case 11:return c->tod_latched?c->tod_latch[r-8u]:c->tod[r-8u];case 12:return c->sdr;case 13:return (uint8_t)(c->icr_flags|(c->irq_line?0x80u:0u));case 14:return (uint8_t)((c->cra&0xeeu)|((c->ta.state&T_START)?1u:0u));case 15:return (uint8_t)((c->crb&0xeeu)|((c->tb.state&T_START)?1u:0u));default:return 0xffu;}}
uint8_t cia6526_read(cia6526 *c,uint8_t r){uint8_t v;r&=0x0fu;if(r==11u&&!c->tod_latched){memcpy(c->tod_latch,c->tod,4);c->tod_latched=1u;}v=cia6526_peek(c,r);if(r==8u)c->tod_latched=0u;if(r==13u){c->icr_flags=0;c->irq_line=0;c->irq_delay=0;}return v;}
static void timer_latch_lo(cia6526_timer *t,uint8_t v){t->latch=(uint16_t)((t->latch&0xff00u)|v);if(t->state&T_LOAD)t->counter=(uint16_t)((t->counter&0xff00u)|v);}
static void timer_latch_hi(cia6526_timer *t,uint8_t v){t->latch=(uint16_t)((t->latch&0x00ffu)|((uint16_t)v<<8));if((t->state&T_LOAD)||!(t->state&T_START))t->counter=t->latch;}
void cia6526_write(cia6526 *c,uint8_t r,uint8_t v){bool alarm;r&=0x0fu;switch(r){case 0:c->pra=v;notify(c,0);break;case 1:c->prb=v;notify(c,1);break;case 2:c->ddra=v;notify(c,0);break;case 3:c->ddrb=v;notify(c,1);break;case 4:timer_latch_lo(&c->ta,v);break;case 5:timer_latch_hi(&c->ta,v);break;case 6:timer_latch_lo(&c->tb,v);break;case 7:timer_latch_hi(&c->tb,v);break;case 8:case 9:case 10:case 11:alarm=(c->crb&0x80u)!=0u;if(alarm)c->alarm[r-8u]=v;else{c->tod[r-8u]=v;if(r==11u)c->tod_stopped=1u;if(r==8u)c->tod_stopped=0u;if(memcmp(c->tod,c->alarm,4)==0)set_source(c,CIA6526_ICR_TOD);}break;case 12:c->sdr=v;if(c->cra&0x40u)c->serial_bits=0u;break;case 13:if(v&0x80u)c->icr_mask|=(uint8_t)(v&0x1fu);else c->icr_mask&=(uint8_t)~(v&0x1fu);if(c->icr_flags&c->icr_mask){if(!c->irq_line&&!c->irq_delay)c->irq_delay=1u;}else c->irq_line=0u;break;case 14:c->cra=(uint8_t)(v&0xefu);timer_ctrl(&c->ta,v,(v&0x20u)==0u);break;case 15:c->crb=(uint8_t)(v&0xefu);timer_ctrl(&c->tb,v,(v&0x60u)==0u);break;default:break;}}
void cia6526_tod_pulse(cia6526 *c){uint8_t div;if(!c)return;div=(c->cra&0x80u)?5u:6u;c->tod_pulses++;if(c->tod_pulses>=div){c->tod_pulses=0;tod_advance(c);}}
bool cia6526_irq(const cia6526 *c){return c&&c->irq_line;}
